const config={url:'https://oxzuunzhsbvumxxbezev.supabase.co',key:'sb_publishable_u2rmM6v1-AdjRLMZSVetRw_MgjeWSL3'};
const $=selector=>document.querySelector(selector);let session=null;
const escapeHtml=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
function status(message,error=false){$('#status').textContent=message;$('#status').className=`status ${error?'error':'success'}`}
function headers(){return {apikey:config.key,Authorization:`Bearer ${session.access_token}`,'Content-Type':'application/json'}}
function showAdmin(){const loggedIn=!!session?.access_token;$('#loginSection').classList.toggle('hidden',loggedIn);$('#grantSection').classList.toggle('hidden',!loggedIn)}
async function rpc(name,body={}){const response=await fetch(`${config.url}/rest/v1/rpc/${name}`,{method:'POST',headers:headers(),body:JSON.stringify(body)});const data=await response.json().catch(()=>null);if(!response.ok)throw new Error(data?.message||data?.hint||`請求失敗 (${response.status})`);return data}
async function login(){status('正在驗證管理員身分……');const response=await fetch(`${config.url}/auth/v1/token?grant_type=password`,{method:'POST',headers:{apikey:config.key,'Content-Type':'application/json'},body:JSON.stringify({email:$('#adminEmail').value.trim(),password:$('#adminPassword').value})});const data=await response.json().catch(()=>null);if(!response.ok)throw new Error(data?.error_description||data?.msg||'登入失敗');session=data;sessionStorage.setItem('wendao-v1-admin-session',JSON.stringify(session));showAdmin();status('管理員已登入');await refreshRecords()}
async function issue(){const publicUid=$('#playerUid').value.trim().toUpperCase(),amount=Math.floor(Number($('#jadeAmount').value)),orderRef=$('#orderRef').value.trim(),note=$('#grantNote').value.trim();if(!/^WD1-[0-9A-F]{8}-[0-9A-F]{4}-[0-9A-F]{4}-[0-9A-F]{4}-[0-9A-F]{12}$/.test(publicUid))throw new Error('UID 格式不正確');if(!Number.isInteger(amount)||amount<1||amount>10000000)throw new Error('靈玉數量需為 1～10,000,000');if(!orderRef)throw new Error('請填寫不重複的訂單編號');if(!confirm(`確定發放 ${amount.toLocaleString()} 靈玉給\n${publicUid}？`))return;$('#issueBtn').disabled=true;status('正在建立發放訂單……');try{await rpc('admin_issue_jade',{p_public_uid:publicUid,p_amount:amount,p_order_ref:orderRef,p_note:note});status(`發放成功：${amount.toLocaleString()} 靈玉`);$('#jadeAmount').value='';$('#orderRef').value='';$('#grantNote').value='';await refreshRecords()}finally{$('#issueBtn').disabled=false}}
async function refreshRecords(){const rows=await rpc('admin_recent_jade_grants');$('#records').innerHTML=rows.length?rows.map(row=>`<article class="record"><b>${escapeHtml(row.public_uid)}・${Number(row.amount).toLocaleString()} 靈玉・${row.status==='claimed'?'已領取':'待領取'}</b><small>訂單 ${escapeHtml(row.order_ref)}・${new Date(row.created_at).toLocaleString('zh-TW')}${row.note?`・${escapeHtml(row.note)}`:''}</small></article>`).join(''):'<p>尚無發放紀錄。</p>'}
$('#loginBtn').onclick=()=>login().catch(error=>status(error.message,true));$('#issueBtn').onclick=()=>issue().catch(error=>status(error.message,true));$('#refreshBtn').onclick=()=>refreshRecords().catch(error=>status(error.message,true));$('#logoutBtn').onclick=()=>{session=null;sessionStorage.removeItem('wendao-v1-admin-session');showAdmin();status('已登出')};
try{session=JSON.parse(sessionStorage.getItem('wendao-v1-admin-session'))}catch{}showAdmin();if(session?.access_token)refreshRecords().catch(()=>{session=null;sessionStorage.removeItem('wendao-v1-admin-session');showAdmin();status('登入已過期，請重新登入',true)});
