(()=>{
'use strict';
const arenaChannel=leaderboardConfig.sessionKey.includes('release')?'formal':'test';
let opponentPool=[],opponentFetchedAt=0,opponentOffset=0,currentView='opponents',busy=false;
const $a=s=>document.querySelector(s),$$a=s=>[...document.querySelectorAll(s)];
function eligible(){return (state.spiritLevel||0)>=40||(state.swordLevel||0)>=40||(state.bodyLevel||0)>=16}
function highestRealm(){return [{name:'練氣',text:realmName(state.spiritLevel||0,spiritRealms),n:(state.spiritLevel||0)/10},{name:'淬劍',text:realmName(state.swordLevel||0,swordRealms),n:(state.swordLevel||0)/10},{name:'煉體',text:bodyRealmName(state.bodyLevel||0),n:(state.bodyLevel||0)/4}].sort((a,b)=>b.n-a.n)[0]}
function arenaCore(x){return Math.max(0,(state[x]||0)+swordPathBonus(x)+equippedAttributeBonus(x)+(state.learnedArts||[]).reduce((n,a)=>n+(a.kind==="ultimate"||a.kind==="fragment"?0:(artKinds[a.kind]?.attribute===x?artTotalEffect(a):0)),0))} function arenaStats(){const r=arenaCore("rootBone"),q=arenaCore("trueQi"),p=arenaCore("physique"),a=arenaCore("agility"),s=arenaCore("spiritualPower");return {maxHp:Math.round(combatHealth(r)),attack:Math.max(12,q*5),qiAttack:Math.max(12,q*5),bodyAttack:Math.max(12,r*2+p*3),defense:Math.max(0,p*20),evasion:combatEvasion(a),accuracy:combatAccuracy(s),crit:combatCritical(s),damageReduction:0}} function arenaPower(){return Math.round(arenaCore("rootBone")*10+arenaCore("trueQi")*25+arenaCore("physique")*20+arenaCore("agility")*15+arenaCore("spiritualPower")*30)} function snapshot(){const stats=arenaStats(),best=highestRealm();return {eligible:eligible(),highest_realm:`${best.name}・${best.text}`,combat_power:arenaPower(),gender:state.gender,sword_embryo:state.swordEmbryo||"",sword_name:state.swordName||"",moves:equippedCombatTechniques().slice(0,2).map(m=>({id:m.id,name:m.name,min:m.min||.8,max:m.max||1,kind:m.kind||"spirit"})),stats}}
async function rpc(name,body={}){let session=await ensureLeaderboardSession(),response=await fetch(`${leaderboardConfig.url}/rest/v1/rpc/${name}`,{method:'POST',headers:leaderboardHeaders(session.access_token),body:JSON.stringify(body)});if(response.status===401){session=await ensureLeaderboardSession(true);response=await fetch(`${leaderboardConfig.url}/rest/v1/rpc/${name}`,{method:'POST',headers:leaderboardHeaders(session.access_token),body:JSON.stringify(body)})}const data=await response.json().catch(()=>null);if(!response.ok)throw new Error(data?.message||'問道臺暫時無法連線');return data}
async function syncProfile(){return eligible()?rpc('arena_sync_profile',{p_channel:arenaChannel,p_name:state.name,p_snapshot:snapshot()}):null}
function modal(){let box=$a('#wendaoArenaModal');if(box)return box;box=document.createElement('div');box.id='wendaoArenaModal';box.className='wendao-arena-modal';box.innerHTML=`<section class="wendao-arena-window"><button class="wendao-arena-close" aria-label="關閉">×</button><header><small>凡間論道・每週競鋒</small><h2>問道臺</h2><p>不借法寶，只以修為、裝備與招式論道</p></header><nav class="wendao-arena-tabs"><button data-arena-view="opponents" class="active">對手</button><button data-arena-view="ranking">排行</button><button data-arena-view="history">戰錄</button></nav><div id="wendaoArenaContent"></div></section>`;document.body.appendChild(box);box.querySelector('.wendao-arena-close').onclick=()=>box.remove();box.onclick=e=>{if(e.target===box)box.remove()};box.querySelectorAll('[data-arena-view]').forEach(b=>b.onclick=()=>renderView(b.dataset.arenaView));return box}
async function claimRewards(){const rows=await rpc('arena_claim_rewards',{p_channel:arenaChannel});for(const r of rows||[]){const id=`arena-week-${arenaChannel}-${r.week_start}`;if(mailbox().some(m=>m.id===id))continue;mailbox().unshift({id,subject:`問道臺每週結算・第${r.rank}名`,sender:'問道臺執事',body:`道友於上週問道臺位列第${r.rank}名，獎勵已隨信奉上。`,sentAt:gameNow(),read:false,claimed:false,attachments:[{type:'item',key:'reputationspiritStone10000Count',name:'一萬靈石',image:itemCatalog.reputationspiritStone10000.image,amount:r.stone_bundle_count}]})}if((rows||[]).length){renderMailButton();save()}}
async function open(){if(!eligible())return toast('三路修行任一路達第五境一階後開放問道臺');if(normalizeAscension().currentRealm==='immortal')return toast('問道臺設於凡間，請先返回凡間');modal();try{await syncProfile();await claimRewards();await renderView('opponents')}catch(e){$a('#wendaoArenaContent').innerHTML=`<p class="arena-empty">${escapeLeaderboardText(e.message)}</p>`}}
async function loadOpponents(force=false){if(force||gameNow()-opponentFetchedAt>=300000||!opponentPool.length){opponentPool=await rpc('arena_opponents',{p_channel:arenaChannel})||[];opponentFetchedAt=gameNow();opponentOffset=0}else opponentOffset+=3;return Array.from({length:Math.min(3,opponentPool.length)},(_,i)=>opponentPool[(opponentOffset+i)%opponentPool.length])}
function opponentRealm(snapshot){if(snapshot.highest_path&&Number.isFinite(Number(snapshot.highest_level))){const level=Number(snapshot.highest_level);return snapshot.highest_path==='body'?bodyRealmName(level):realmName(level,snapshot.highest_path==='sword'?swordRealms:spiritRealms)}return snapshot.highest_realm||'凡境未明'}
function opponentCard(row){const s=row.snapshot||{},moves=(s.moves||[]).slice(0,2);return `<article class="arena-opponent"><div><small>積分 ${row.score}</small><b>${escapeLeaderboardText(row.player_name)}</b><span>${escapeLeaderboardText(opponentRealm(s))}</span></div><strong>戰力 ${formatCombatPower(s.combat_power||0)}</strong><p>${moves.length?moves.map(m=>escapeLeaderboardText(m.name)).join('・'):'未配置招式'}</p><button data-arena-challenge="${row.user_id}">挑戰</button></article>`}
async function renderView(view=currentView,force=false){currentView=view;const box=modal(),content=box.querySelector('#wendaoArenaContent');box.querySelectorAll('[data-arena-view]').forEach(b=>b.classList.toggle('active',b.dataset.arenaView===view));content.innerHTML='<p class="arena-loading">正在展開問道名冊……</p>';try{if(view==='opponents'){const [status,opponents]=await Promise.all([rpc('arena_status',{p_channel:arenaChannel}),loadOpponents(force)]);content.innerHTML=`<section class="arena-status"><span><small>目前積分</small><b>${status.score}</b></span><span><small>本週名次</small><b>${status.rank||'未上榜'}</b></span><span><small>今日可戰</small><b>${status.free_remaining+status.bought_available} / 20</b></span></section><div class="arena-purchase"><button data-arena-buy="stone" ${status.stone_bought>=5?'disabled':''}>5000靈石・挑戰1次<small>今日 ${status.stone_bought}/5</small></button><button data-arena-buy="jade" ${status.jade_bought>=5?'disabled':''}>10靈玉・挑戰1次<small>今日 ${status.jade_bought}/5</small></button><button id="arenaRefresh">刷新對手<small>名冊每5分鐘更新</small></button></div><div class="arena-opponents">${opponents.length?opponents.map(opponentCard).join(''):'<p class="arena-empty">目前沒有可挑戰的修士；待其他玩家進入問道臺後便會出現。</p>'}</div>`;content.querySelectorAll('[data-arena-challenge]').forEach(b=>b.onclick=()=>challenge(b.dataset.arenaChallenge));content.querySelectorAll('[data-arena-buy]').forEach(b=>b.onclick=()=>buy(b.dataset.arenaBuy));$a('#arenaRefresh').onclick=()=>renderView('opponents',gameNow()-opponentFetchedAt>=300000)}else if(view==='ranking'){const [status,rows]=await Promise.all([rpc('arena_status',{p_channel:arenaChannel}),rpc('arena_rankings',{p_channel:arenaChannel})]);content.innerHTML=`<div class="arena-own-rank">我的名次：${status.rank||'未上榜'}・積分 ${status.score}</div><div class="arena-ranking">${(rows||[]).map(r=>`<article><strong>${r.rank}</strong><b>${escapeLeaderboardText(r.player_name)}</b><span>${r.score}分・${r.wins}勝 ${r.losses}敗</span></article>`).join('')||'<p class="arena-empty">本週尚無戰績</p>'}</div>`}else{const rows=await rpc('arena_history',{p_channel:arenaChannel}),uid=readLeaderboardSession()?.user?.id;content.innerHTML=`<div class="arena-history">${(rows||[]).map(r=>{const mine=r.was_challenger,won=r.winner_id===uid,foe=mine?r.defender_name:r.challenger_name,d=mine?r.challenger_delta:r.defender_delta;return `<article class="${won?'won':'lost'}"><b>${won?'勝':'敗'}・${escapeLeaderboardText(foe)}</b><span>${d>=0?'+':''}${d}分</span><small>${new Date(r.created_at).toLocaleString()}</small></article>`}).join('')||'<p class="arena-empty">尚無對戰紀錄</p>'}</div>`}}catch(e){content.innerHTML=`<p class="arena-empty">${escapeLeaderboardText(e.message)}</p>`}}
async function buy(kind){if(busy)return;const price=kind==='stone'?5000:10,key=kind==='stone'?'spiritStone':'spiritJade',label=kind==='stone'?'靈石':'靈玉';if(state[key]<price)return toast(`${label}不足`);busy=true;try{await rpc('arena_buy_attempt',{p_kind:kind});state[key]-=price;save();render();toast('問道臺挑戰次數 +1');await renderView('opponents')}catch(e){toast(e.message)}finally{busy=false}}
async function challenge(userId){if(busy)return;busy=true;try{await syncProfile();const data=await rpc('arena_begin_challenge',{p_channel:arenaChannel,p_defender:userId});modal().remove();startBattle(data)}catch(e){toast(e.message)}finally{busy=false}}
function startBattle(data){const s=data.opponent||{},t=s.stats||{},maxHp=Math.max(125,Number(t.maxHp)||125),player=battlePlayerStats();clearTimeout(battleTimer);startBgm('battle');battle={active:true,resolved:false,mode:'arena',arenaMatchId:data.match_id,arenaOpponentSnapshot:s,enemyMoveIndex:0,round:1,completedRounds:0,playerMoveIndex:0,player:{...player,hp:player.maxHp},enemy:{...t,maxHp,hp:maxHp,attack:Math.max(1,Number(t.attack)||1),defense:Math.max(0,Number(t.defense)||0),evasion:Math.max(0,Number(t.evasion)||0),accuracy:Math.max(0,Number(t.accuracy)||0),crit:Math.max(0,Number(t.crit)||0),name:data.opponent_name||'無名修士',race:'human'},logs:[]};$a('#battleModal').classList.remove('hidden');$a('#battleStage').classList.remove('hidden');$a('#battleResult').classList.add('hidden');$a('#playerSilhouette').className=`battle-silhouette ${state.gender==='女'?'silhouette-player-female':'silhouette-player-male'}`;$a('#enemySilhouette').className=`battle-silhouette arena-enemy ${s.gender==='女'?'silhouette-player-female':'silhouette-player-male'} ${s.sword_embryo?'has-arena-sword':''}`;$a('#battlePlayerName').textContent=state.name;$a('#battleEnemyName').textContent=battle.enemy.name;$a('.battle-arena').classList.add('wendao-battle');$a('.battle-arena').style.backgroundImage="linear-gradient(#f6fff344,#d9eee033),url('assets/qstyle-v2/wendao-arena-battle-bg-v1.png')";$a('#battleLog').innerHTML=`<p><b>問道臺</b>・雙方法寶均不生效・對手招式：${(s.moves||[]).map(m=>escapeLeaderboardText(m.name)).join('、')||'凝念馭元'}</p>`;syncBattleWeapon();updateBattleUi();battleTimer=setTimeout(playerBattleTurn,700)}
async function submit(won,id){try{const r=await rpc('arena_finish_match',{p_match:id,p_won:won});toast(`問道臺積分 ${r.delta>=0?'+':''}${r.delta}・目前 ${r.score}`);opponentFetchedAt=0;await syncProfile()}catch(e){toast(e.message)}}
const originalArtifact=activeBattleArtifact;activeBattleArtifact=function(){return battle?.mode==='arena'?'':originalArtifact()};
const originalEnemyTurn=enemyBattleTurn;enemyBattleTurn=function(){if(battle?.mode!=='arena')return originalEnemyTurn();const choices=battle.arenaOpponentSnapshot?.moves||[],move=choices[battle.enemyMoveIndex++%Math.max(1,choices.length)]||{name:'凝念馭元',min:.8,max:1},mult=(move.min||.8)+Math.random()*((move.max||1)-(move.min||.8)),hit=damageRoll(battle.enemy,battle.player,mult),damage=Math.max(hit.dodged?0:1,Math.round(hit.damage*(1-(battle.player.damageReduction||0))));battle.player.hp=Math.max(0,battle.player.hp-damage);animateBattleStrike('#enemySilhouette','#playerSilhouette',{...hit,damage},move);appendBattleLog(hit.dodged?`${state.name}避開了${battle.enemy.name}的${move.name}。`:`${battle.enemy.name}使出${move.name}，對${state.name}造成了${formatBattleNumber(damage)}傷害。`,'enemy');battle.completedRounds++;updateBattleUi();if(battle.player.hp<=0)return setTimeout(()=>finishBattle(false,'你氣力不支，本次問道落敗。'),650);battle.round++;updateBattleUi();battleTimer=setTimeout(playerBattleTurn,900)};
const originalFinish=finishBattle;finishBattle=function(won,reason){const id=battle?.mode==='arena'?battle.arenaMatchId:null;originalFinish(won,reason);if(id)submit(won,id)};
const originalForceEnd=forceEndBattle;forceEndBattle=function(){if(battle?.mode==='arena'&&battle.completedRounds>=3)return finishBattle(false,'你主動認輸，本次問道落敗。');return originalForceEnd()};
const originalClose=closeBattle;closeBattle=function(){const arena=battle?.mode==='arena';originalClose();$a('.battle-arena')?.classList.remove('wendao-battle');if(arena)setTimeout(open,100)};
const originalRender=render;render=function(...args){const value=originalRender(...args),button=$a('#wendaoArenaButton');if(button)button.classList.toggle('hidden',!eligible()||normalizeAscension().currentRealm==='immortal');return value};
function openArenaPurchase(){const old=$a('.arena-buy-modal');if(old)old.remove();const layer=document.createElement('div');layer.className='arena-buy-modal';layer.innerHTML='<div class="arena-buy-window"><button class="arena-buy-close" aria-label="關閉">×</button><h3>購買問道臺次數</h3><p>每日免費次數用盡後，購買次數可直接突破 10 次。</p><button data-arena-buy="stone">5000靈石・挑戰1次<small>每日限購5次</small></button><button data-arena-buy="jade">10靈玉・挑戰1次<small>每日限購5次</small></button></div>';const box=$a('.wendao-arena-window');box.appendChild(layer);layer.querySelector('.arena-buy-close').onclick=()=>layer.remove();layer.onclick=e=>{if(e.target===layer)layer.remove()};layer.querySelectorAll('[data-arena-buy]').forEach(b=>b.onclick=()=>buy(b.dataset.arenaBuy))}
function decorateArenaActions(){const wrap=$a('.arena-purchase');if(!wrap)return;const refresh=wrap.querySelector('#arenaRefresh'),buyButtons=[...wrap.querySelectorAll('[data-arena-buy]')];if(!refresh||wrap.dataset.compact)return;wrap.dataset.compact='true';refresh.innerHTML='刷新對手';refresh.className='arena-refresh-button';buyButtons.forEach(button=>button.remove());const buyButton=document.createElement('button');buyButton.className='arena-buy-button';buyButton.textContent='購買次數';buyButton.onclick=openArenaPurchase;wrap.append(refresh,buyButton);const count=$a('.arena-status span:nth-child(3) b');if(count)count.textContent=count.textContent.replace(/\s*\/\s*20/,' / 10')}
const originalRenderView=renderView;renderView=async function(...args){const result=await originalRenderView(...args);if(currentView==='opponents')decorateArenaActions();return result}
$a('#wendaoArenaButton').onclick=open;
render();
})();
