(()=>{
'use strict';
const channel=leaderboardConfig.sessionKey.includes('release')?'formal':'test';
const choiceMeta={rock:{name:'石頭',icon:'✊'},scissors:{name:'剪刀',icon:'✌️'},paper:{name:'布',icon:'🖐️'}};
let busy=false,currentView='menu';
const q=s=>document.querySelector(s);
async function rpc(name,body={}){let session=await ensureLeaderboardSession(),response=await fetch(`${leaderboardConfig.url}/rest/v1/rpc/${name}`,{method:'POST',headers:leaderboardHeaders(session.access_token),body:JSON.stringify(body)});if(response.status===401){session=await ensureLeaderboardSession(true);response=await fetch(`${leaderboardConfig.url}/rest/v1/rpc/${name}`,{method:'POST',headers:leaderboardHeaders(session.access_token),body:JSON.stringify(body)})}const data=await response.json().catch(()=>null);if(!response.ok)throw new Error(data?.message||'藏機局暫時無法連線');return data}
function modal(){let layer=q('#cangjiModal');if(layer)return layer;layer=document.createElement('div');layer.id='cangjiModal';layer.className='cangji-modal';layer.innerHTML=`<section class="cangji-window"><button class="cangji-close" aria-label="關閉">×</button><header><small>三手藏機・落子無悔</small><h2>藏機局</h2><p>石剋剪・剪剋布・布剋石</p></header><nav class="cangji-menu"><button data-cangji-view="create">設局</button><button data-cangji-view="open">應局</button><button data-cangji-view="owned">檢視已設之局</button><button data-cangji-view="cancel">撤局</button></nav><div id="cangjiContent" class="cangji-content"></div></section>`;document.body.append(layer);layer.querySelector('.cangji-close').onclick=()=>layer.remove();layer.onclick=e=>{if(e.target===layer)layer.remove()};layer.querySelectorAll('[data-cangji-view]').forEach(button=>button.onclick=()=>show(button.dataset.cangjiView));return layer}
function setActive(view){currentView=view;modal().querySelectorAll('[data-cangji-view]').forEach(button=>button.classList.toggle('active',button.dataset.cangjiView===view))}
function loading(text='正在展開藏機名冊……'){q('#cangjiContent').innerHTML=`<p class="cangji-empty">${text}</p>`}
function choiceButtons(selected=''){return `<div class="cangji-choices">${Object.entries(choiceMeta).map(([key,value])=>`<button data-cangji-choice="${key}" class="${selected===key?'active':''}"><b>${value.icon}</b><span>${value.name}</span></button>`).join('')}</div>`}
function bindChoice(container,onSelect){container.querySelectorAll('[data-cangji-choice]').forEach(button=>button.onclick=()=>{container.querySelectorAll('[data-cangji-choice]').forEach(item=>item.classList.toggle('active',item===button));onSelect(button.dataset.cangjiChoice)})}
function updateCurrency(){q('#spiritStoneAmount').textContent=formatLargeNumber(state.spiritStone);save()}
function resultText(outcome){return outcome==='win'?'勝局':outcome==='draw'?'和局':'敗局'}
function outcomeClass(outcome){return outcome==='win'?'won':outcome==='draw'?'draw':'lost'}
function reveal(data,role='responder'){
  const layer=document.createElement('div');layer.className='cangji-result-layer';
  const mine=role==='responder'?data.responder_choice:data.creator_choice,foe=role==='responder'?data.creator_choice:data.responder_choice;
  layer.innerHTML=`<section class="cangji-result ${outcomeClass(data.outcome)}"><small>藏機局・${escapeLeaderboardText(data.game_code||data.game_no)}</small><h3>${resultText(data.outcome)}</h3><div><span><b>${choiceMeta[mine]?.icon||'？'}</b>你・${choiceMeta[mine]?.name||'未知'}</span><i>對</i><span><b>${choiceMeta[foe]?.icon||'？'}</b>${escapeLeaderboardText(data.creator_name||data.opponent_name||'道友')}・${choiceMeta[foe]?.name||'未知'}</span></div><p>押注 ${formatLargeNumber(data.wager)} 靈石・實得 ${formatLargeNumber(data.payout)} 靈石・手續費 ${formatLargeNumber(data.fee)} 靈石</p><button>收下結果</button></section>`;
  document.body.append(layer);layer.querySelector('button').onclick=()=>layer.remove();
}
async function showCreate(){setActive('create');let selected='';q('#cangjiContent').innerHTML=`<section class="cangji-create"><h3>設下藏機之局</h3><p>出拳將保持隱藏，直到有道友應局。</p>${choiceButtons()}<label>押注靈石<input id="cangjiWager" type="number" inputmode="numeric" min="5000" max="30000" step="500" value="5000"></label><small>5,000～30,000靈石，以500為單位；最多同時保留5局，結算領取或撤局後才會釋出名額。</small><p id="cangjiWagerError" class="cangji-form-error" aria-live="polite"></p><button id="cangjiCreate" disabled>押注設局</button></section>`;const area=q('.cangji-create'),wagerInput=q('#cangjiWager'),wagerError=q('#cangjiWagerError');const clearWagerError=()=>wagerError.textContent='';wagerInput.addEventListener('input',clearWagerError);bindChoice(area,key=>{selected=key;q('#cangjiCreate').disabled=false});q('#cangjiCreate').onclick=async()=>{if(busy)return;const wager=Math.trunc(Number(wagerInput.value));clearWagerError();if(wager%500){wagerError.textContent='押注金額需為500的倍數';return}if(wager<5000||wager>30000){wagerError.textContent='押注金額需介於5,000～30,000靈石';return}if(state.spiritStone<wager){toast('靈石不足，無法設局');return}busy=true;q('#cangjiCreate').disabled=true;try{await rpc('cangji_create_game',{p_channel:channel,p_name:state.name,p_choice:selected,p_wager:wager});state.spiritStone-=wager;updateCurrency();toast(`設局完成・${formatLargeNumber(wager)}靈石已投入獎池`);await showOwned()}catch(e){if(/上限 5\/5|尚未結算/.test(e.message))wagerError.textContent='設局已滿5局，請先領取已結算結果或撤回待應之局';else toast(e.message);q('#cangjiCreate').disabled=false}finally{busy=false}}}
async function showOpen(){setActive('open');loading();try{const rows=await rpc('cangji_open_games',{p_channel:channel})||[];const content=q('#cangjiContent');content.innerHTML=`<section class="cangji-list">${rows.length?rows.map(row=>`<article data-game="${row.id}"><div><b>${escapeLeaderboardText(row.game_code||row.game_no)}・${escapeLeaderboardText(row.creator_name)}</b><small>${new Date(row.created_at).toLocaleString()}</small></div><strong>${formatLargeNumber(row.wager)} 靈石</strong><button data-answer="${row.id}" data-wager="${row.wager}" data-name="${escapeLeaderboardText(row.creator_name)}">應局</button></article>`).join(''):'<p class="cangji-empty">目前沒有等待應局的挑戰。</p>'}</section>`;content.querySelectorAll('[data-answer]').forEach(button=>button.onclick=()=>answer(button))}catch(e){loading(escapeLeaderboardText(e.message))}}
function answer(button){const wager=Number(button.dataset.wager);if(state.spiritStone<wager)return toast('靈石不足，無法應局');let selected='';const layer=document.createElement('div');layer.className='cangji-pick-layer';layer.innerHTML=`<section class="cangji-pick"><button class="cangji-pick-close">×</button><h3>應下此局</h3><p>押注 ${formatLargeNumber(wager)} 靈石・選擇後立即揭手</p>${choiceButtons()}<button class="cangji-answer-confirm" disabled>確認出拳</button></section>`;document.body.append(layer);layer.querySelector('.cangji-pick-close').onclick=()=>layer.remove();bindChoice(layer,key=>{selected=key;layer.querySelector('.cangji-answer-confirm').disabled=false});layer.querySelector('.cangji-answer-confirm').onclick=async()=>{if(busy)return;if(state.spiritStone<wager){layer.remove();return toast('靈石不足，無法應局')}busy=true;layer.querySelector('.cangji-answer-confirm').disabled=true;try{const data=await rpc('cangji_accept_game',{p_game:button.dataset.answer,p_name:state.name,p_choice:selected});state.spiritStone+=Number(data.payout)-wager;updateCurrency();button.closest('article')?.remove();layer.remove();reveal(data);render()}catch(e){toast(e.message);layer.remove();button.closest('article')?.remove()}finally{busy=false}}}
async function showOwned(){setActive('owned');loading();try{const rows=await rpc('cangji_creator_games',{p_channel:channel})||[],visible=rows.filter(row=>row.status==='open'||!row.claimed),claimable=visible.some(row=>row.status==='resolved');q('#cangjiContent').innerHTML=`${claimable?'<button id="cangjiClaimAll" class="cangji-claim-all">全部領取</button>':''}<section class="cangji-list owned">${visible.length?visible.map(row=>`<article class="${row.status==='resolved'?outcomeClass(row.outcome):''}" data-game="${row.id}"><div><b>${escapeLeaderboardText(row.game_code||row.game_no)}・${row.status==='open'?'等待應局':resultText(row.outcome)}</b><small>${row.status==='open'?'出拳尚未揭曉':`${choiceMeta[row.creator_choice]?.name} 對 ${choiceMeta[row.responder_choice]?.name}・${escapeLeaderboardText(row.opponent_name||'道友')}`}</small></div><strong>${formatLargeNumber(row.wager)} 靈石</strong>${row.status==='resolved'?`<p>實得 ${formatLargeNumber(row.payout)}${row.outcome==='win'?`・手續費 ${formatLargeNumber(row.fee)}`:''}</p>`:'<span>藏機未揭</span>'}</article>`).join(''):'<p class="cangji-empty">目前沒有待領取或等待應局的紀錄。</p>'}</section>`;q('#cangjiClaimAll')?.addEventListener('click',claimAll)}catch(e){loading(escapeLeaderboardText(e.message))}}
async function claimAll(){const button=q('#cangjiClaimAll');if(busy||!button)return;busy=true;button.disabled=true;try{const data=await rpc('cangji_claim_all_games',{p_channel:channel});state.spiritStone+=Number(data.payout);updateCurrency();toast(`已領取 ${Number(data.count)||0} 局・共 ${formatLargeNumber(Number(data.payout)||0)} 靈石`);render();await showOwned()}catch(e){button.disabled=false;toast(e.message)}finally{busy=false}}
async function showCancel(){setActive('cancel');loading();try{const rows=(await rpc('cangji_creator_games',{p_channel:channel})||[]).filter(row=>row.status==='open'),refund=rows.reduce((sum,row)=>sum+Number(row.wager),0),numbers=rows.map(row=>escapeLeaderboardText(row.game_code||row.game_no)).join('、');q('#cangjiContent').innerHTML=rows.length?`<section class="cangji-cancel-all"><h3>撤回全部待應之局</h3><p>${numbers}</p><p>共 ${rows.length} 局・退回 ${formatLargeNumber(refund)} 靈石</p><button id="cangjiCancelAll">全部撤局</button></section>`:'<p class="cangji-empty">目前沒有可以撤回的局。</p>';q('#cangjiCancelAll')?.addEventListener('click',cancelAll)}catch(e){loading(escapeLeaderboardText(e.message))}}
async function cancelAll(){const button=q('#cangjiCancelAll');if(busy||!button)return;busy=true;button.disabled=true;try{const data=await rpc('cangji_cancel_all_games',{p_channel:channel});state.spiritStone+=Number(data.refund);updateCurrency();toast(`已撤回 ${Number(data.count)||0} 局・退回 ${formatLargeNumber(Number(data.refund)||0)} 靈石`);render();await showCancel()}catch(e){button.disabled=false;toast(e.message)}finally{busy=false}}
async function show(view){if(view==='create')return showCreate();if(view==='open')return showOpen();if(view==='owned')return showOwned();if(view==='cancel')return showCancel();setActive('menu');q('#cangjiContent').innerHTML='<p class="cangji-intro">藏一手天機，候一位道友。勝方取回自身押注並獲得對手押注的98%；和局全額退還。</p>'}
function open(){if(normalizeAscension().currentRealm==='immortal')return toast('藏機局設於凡間，請先返回凡間');modal();show('menu')}
function syncButton(){q('#cangjiButton')?.classList.toggle('hidden',normalizeAscension().currentRealm==='immortal')}
q('#cangjiButton').onclick=open;
const previousRender=render;render=function(...args){const value=previousRender(...args);syncButton();return value};
syncButton();render();
})();
