create table if not exists private.player_equipment_profiles(user_id uuid not null references auth.users(id) on delete cascade,channel text not null check(channel in('formal','test')),imported boolean not null default false,revision bigint not null default 1,updated_at timestamptz not null default now(),primary key(user_id,channel));
create table if not exists private.player_equipment_items(user_id uuid not null references auth.users(id) on delete cascade,channel text not null check(channel in('formal','test')),item_id text not null,slot text not null check(slot in('crown','robe','bracer','belt','boots','pendant','ring')),tier integer not null check(tier between 1 and 9),quality text not null check(quality in('normal','rare')),value integer not null default 0 check(value>=0),affixes jsonb not null default '[]'::jsonb check(jsonb_typeof(affixes)='array'),equipped boolean not null default false,created_at timestamptz not null default now(),primary key(user_id,channel,item_id));
create unique index if not exists player_equipment_one_per_slot on private.player_equipment_items(user_id,channel,slot) where equipped;
alter table private.player_equipment_profiles enable row level security;alter table private.player_equipment_items enable row level security;revoke all on private.player_equipment_profiles,private.player_equipment_items from public,anon,authenticated;

create or replace function private.equipment_bounds(p_tier integer,p_slot text,p_quality text) returns integer[] language plpgsql immutable set search_path='' as $$
declare idx integer:=array_position(array['crown','robe','bracer','belt','boots'],p_slot);tables jsonb;
begin if idx is null then return array[0,0];end if;tables:=case when p_quality='rare' then '[[[13,17],[20,25],[40,50],[16,20],[26,34]],[[29,36],[43,55],[86,109],[34,44],[57,73]],[[57,73],[86,109],[172,218],[69,87],[114,146]],[[99,126],[148,189],[297,378],[119,151],[198,252]],[[154,196],[231,294],[462,588],[185,235],[308,392]],[[226,287],[338,431],[676,861],[271,344],[451,574]],[[323,411],[484,616],[968,1232],[387,493],[645,821]],[[369,469],[553,704],[1106,1408],[442,563],[737,939]],[[528,672],[792,1008],[1584,2016],[634,806],[1056,1344]]]'::jsonb else '[[[8,12],[13,17],[26,34],[10,14],[17,23]],[[18,25],[28,37],[55,75],[22,30],[37,50]],[[37,50],[55,75],[110,150],[44,60],[74,100]],[[64,86],[96,129],[191,259],[76,103],[128,172]],[[99,134],[149,201],[298,402],[119,161],[198,268]],[[145,196],[218,295],[436,589],[174,236],[290,393]],[[208,281],[312,422],[623,843],[249,337],[416,562]],[[237,321],[356,482],[712,964],[285,385],[475,642]],[[340,460],[510,690],[1020,1380],[408,552],[680,920]]]'::jsonb end;return array[(tables->(p_tier-1)->(idx-1)->>0)::integer,(tables->(p_tier-1)->(idx-1)->>1)::integer];end $$;
create or replace function private.equipment_valid(p_slot text,p_tier integer,p_quality text,p_value integer,p_affixes jsonb) returns boolean language plpgsql immutable set search_path='' as $$
declare bounds integer[];a jsonb;count_needed integer:=case when p_tier<=3 then 1 when p_tier<=6 then 2 else 3 end;max_affix numeric:=case when p_tier<=3 then 2 when p_tier<=6 then 5 else 8 end;
begin if p_slot not in('crown','robe','bracer','belt','boots','pendant','ring') or p_tier not between 1 and 9 or p_quality not in('normal','rare') or jsonb_typeof(p_affixes)<>'array' then return false;end if;if p_slot in('crown','robe','bracer','belt','boots') then bounds:=private.equipment_bounds(p_tier,p_slot,p_quality);return p_value between bounds[1] and bounds[2] and jsonb_array_length(p_affixes)=0;end if;if p_value<>0 or jsonb_array_length(p_affixes)<>count_needed then return false;end if;for a in select value from jsonb_array_elements(p_affixes) loop if a->>'element' not in('金','木','水','火','土') or (a->>'value')::numeric not between 1 and max_affix then return false;end if;end loop;return true;exception when others then return false;end $$;
create or replace function private.equipment_snapshot(p_user uuid,p_channel text) returns jsonb language sql stable security definer set search_path='' as $$select jsonb_build_object('revision',coalesce((select revision from private.player_equipment_profiles where user_id=p_user and channel=p_channel),0),'items',coalesce((select jsonb_agg(jsonb_build_object('id',item_id,'slot',slot,'tier',tier,'quality',quality,'value',value,'affixes',affixes,'equipped',equipped) order by created_at,item_id) from private.player_equipment_items where user_id=p_user and channel=p_channel),'[]'::jsonb))$$;

create or replace function public.player_equipment_bootstrap(p_channel text,p_legacy_items jsonb,p_legacy_equipped jsonb) returns jsonb language plpgsql security definer set search_path='' as $$
declare uid uuid:=(select auth.uid());profile private.player_equipment_profiles;x jsonb;legacy_id text;should_equip boolean;slot_used text[]:='{}';
begin if uid is null then raise exception '需要重新登入';end if;if p_channel not in('formal','test') or jsonb_typeof(coalesce(p_legacy_items,'[]'))<>'array' or jsonb_array_length(coalesce(p_legacy_items,'[]'))>500 then raise exception '裝備資料不正確';end if;perform pg_advisory_xact_lock(hashtext(uid::text||'-equipment-'||p_channel));insert into private.player_equipment_profiles(user_id,channel) values(uid,p_channel) on conflict do nothing;select * into profile from private.player_equipment_profiles where user_id=uid and channel=p_channel for update;if not profile.imported then for x in select value from jsonb_array_elements(coalesce(p_legacy_items,'[]')) loop legacy_id:=left(coalesce(x->>'id',''),80);if legacy_id<>'' and private.equipment_valid(x->>'slot',coalesce((x->>'tier')::integer,0),x->>'quality',coalesce((x->>'value')::integer,0),coalesce(x->'affixes','[]')) then should_equip:=coalesce(p_legacy_equipped->>(x->>'slot'),'')=legacy_id and not (x->>'slot'=any(slot_used));insert into private.player_equipment_items(user_id,channel,item_id,slot,tier,quality,value,affixes,equipped) values(uid,p_channel,legacy_id,x->>'slot',(x->>'tier')::integer,x->>'quality',(x->>'value')::integer,x->'affixes',should_equip) on conflict do nothing;if should_equip then slot_used:=array_append(slot_used,x->>'slot');end if;end if;end loop;update private.player_equipment_profiles set imported=true,revision=revision+1,updated_at=now() where user_id=uid and channel=p_channel;end if;return private.equipment_snapshot(uid,p_channel);exception when invalid_text_representation or numeric_value_out_of_range then raise exception '裝備資料不正確';end $$;

create or replace function public.player_equipment_forge(p_channel text,p_slot text,p_tier integer,p_quality text,p_request_id uuid) returns jsonb language plpgsql security definer set search_path='' as $$
declare uid uuid:=(select auth.uid());p private.player_progression_states;profile private.player_equipment_profiles;bounds integer[];item_value integer:=0;item_affixes jsonb:='[]';item_id text:=gen_random_uuid()::text;main_keys text[]:=array['mainlineMaterial_xuansi','mainlineMaterial_xuanjuan','mainlineMaterial_xuanpi','mainlineMaterial_lingpi','mainlineMaterial_fengpi','mainlineMaterial_lingyu','mainlineMaterial_lingjing'];slot_index integer:=array_position(array['crown','robe','bracer','belt','boots','pendant','ring'],p_slot);needs integer[][]:=array[[3,1,1],[4,2,1],[5,3,1],[6,4,2],[7,5,2],[8,6,3],[9,7,3],[10,8,4],[12,10,5]];max_tier integer;k text;need_amount integer;b private.player_mail_item_balances;elements text[]:=array['金','木','水','火','土'];picked text[]:='{}';element text;affix_count integer;low_value integer;high_value integer;i integer;roll integer;
begin if uid is null then raise exception '需要重新登入';end if;if p_channel not in('formal','test') or slot_index is null or p_tier not between 1 and 9 or p_quality not in('normal','rare') or p_request_id is null then raise exception '鍛造資料不正確';end if;if exists(select 1 from private.player_state_events where user_id=uid and channel=p_channel and request_id=p_request_id) then raise exception '重複的鍛造請求';end if;perform pg_advisory_xact_lock(hashtext(uid::text||'-equipment-'||p_channel));select * into p from private.player_progression_states where user_id=uid and channel=p_channel;max_tier:=least(9,greatest(p.spirit_level/10+1,p.sword_level/10+1,p.body_level/4+1));if p_tier>max_tier then raise exception '目前境界不足';end if;
 foreach k in array array[main_keys[slot_index],'forgeTierMaterial_'||p_tier]||case when p_quality='rare' then array['equipmentSpiritCore'] else array[]::text[] end loop need_amount:=case when k=main_keys[slot_index] then needs[p_tier][1] when k='forgeTierMaterial_'||p_tier then needs[p_tier][2] else needs[p_tier][3] end;select * into b from private.player_mail_item_balances where user_id=uid and channel=p_channel and item_key=k for update;if coalesce(b.amount,0)<need_amount then raise exception '製作素材不足';end if;update private.player_mail_item_balances set amount=amount-need_amount,updated_at=now() where user_id=uid and channel=p_channel and item_key=k;end loop;
 if slot_index<=5 then bounds:=private.equipment_bounds(p_tier,p_slot,p_quality);item_value:=bounds[1]+floor(random()*(bounds[2]-bounds[1]+1));else affix_count:=case when p_tier<=3 then 1 when p_tier<=6 then 2 else 3 end;low_value:=case when p_tier<=3 then 10 when p_tier<=6 then 20 else 30 end;high_value:=case when p_tier<=3 then 20 when p_tier<=6 then 50 else 80 end;for i in 1..affix_count loop loop element:=elements[1+floor(random()*5)::integer];exit when not element=any(picked);end loop;picked:=array_append(picked,element);roll:=low_value+floor(random()*(high_value-low_value+1));if p_quality='rare' then roll:=greatest(roll,low_value+floor(random()*(high_value-low_value+1)));end if;item_affixes:=item_affixes||jsonb_build_array(jsonb_build_object('element',element,'value',roll/10.0));end loop;end if;
 insert into private.player_equipment_profiles(user_id,channel,imported) values(uid,p_channel,true) on conflict do nothing;insert into private.player_equipment_items(user_id,channel,item_id,slot,tier,quality,value,affixes) values(uid,p_channel,item_id,p_slot,p_tier,p_quality,item_value,item_affixes);update private.player_equipment_profiles set revision=revision+1,updated_at=now() where user_id=uid and channel=p_channel returning * into profile;insert into private.player_state_events(user_id,channel,revision,event_type,request_id,payload) values(uid,p_channel,profile.revision,'equipment_forged',p_request_id,jsonb_build_object('itemId',item_id,'slot',p_slot,'tier',p_tier,'quality',p_quality));return private.equipment_snapshot(uid,p_channel);end $$;

create or replace function public.player_equipment_set(p_channel text,p_item_id text,p_equip boolean,p_request_id uuid) returns jsonb language plpgsql security definer set search_path='' as $$
declare uid uuid:=(select auth.uid());item private.player_equipment_items;profile private.player_equipment_profiles;
begin if uid is null then raise exception '需要重新登入';end if;if p_channel not in('formal','test') or p_request_id is null then raise exception '裝備請求不正確';end if;if exists(select 1 from private.player_state_events where user_id=uid and channel=p_channel and request_id=p_request_id) then raise exception '重複的裝備請求';end if;perform pg_advisory_xact_lock(hashtext(uid::text||'-equipment-'||p_channel));select * into item from private.player_equipment_items where user_id=uid and channel=p_channel and item_id=p_item_id for update;if item.item_id is null then raise exception '找不到此裝備';end if;if p_equip then update private.player_equipment_items set equipped=false where user_id=uid and channel=p_channel and slot=item.slot and equipped;update private.player_equipment_items set equipped=true where user_id=uid and channel=p_channel and item_id=p_item_id;else update private.player_equipment_items set equipped=false where user_id=uid and channel=p_channel and item_id=p_item_id;end if;update private.player_equipment_profiles set revision=revision+1,updated_at=now() where user_id=uid and channel=p_channel returning * into profile;insert into private.player_state_events(user_id,channel,revision,event_type,request_id,payload) values(uid,p_channel,profile.revision,case when p_equip then 'equipment_equipped' else 'equipment_unequipped' end,p_request_id,jsonb_build_object('itemId',p_item_id,'slot',item.slot));return private.equipment_snapshot(uid,p_channel);end $$;

revoke all on function private.equipment_bounds(integer,text,text),private.equipment_valid(text,integer,text,integer,jsonb),private.equipment_snapshot(uuid,text) from public,anon,authenticated;
revoke execute on function public.player_equipment_bootstrap(text,jsonb,jsonb),public.player_equipment_forge(text,text,integer,text,uuid),public.player_equipment_set(text,text,boolean,uuid) from public,anon;
grant execute on function public.player_equipment_bootstrap(text,jsonb,jsonb),public.player_equipment_forge(text,text,integer,text,uuid),public.player_equipment_set(text,text,boolean,uuid) to authenticated;
