create table if not exists private.player_divine_roaming_states(
 user_id uuid not null references auth.users(id) on delete cascade,channel text not null check(channel in('formal','test')),
 unlocked boolean not null default false,legacy_imported boolean not null default false,day_key date not null default (timezone('Asia/Taipei',now()))::date,used integer not null default 0 check(used between 0 and 100),
 job_stage integer check(job_stage between 1 and 18),job_total integer not null default 0 check(job_total between 0 and 100),job_completed integer not null default 0 check(job_completed between 0 and 100),next_at timestamptz,return_requested boolean not null default false,pending_stage integer,pending_total integer not null default 0,
 harvest jsonb not null default '{}'::jsonb check(jsonb_typeof(harvest)='object'),revision bigint not null default 1,updated_at timestamptz not null default now(),primary key(user_id,channel)
);
alter table private.player_divine_roaming_states enable row level security;revoke all on private.player_divine_roaming_states from public,anon,authenticated;

create or replace function private.divine_add(h jsonb,k text,v integer) returns jsonb language sql immutable set search_path='' as $$select case when v<=0 then h else jsonb_set(h,array[k],to_jsonb(coalesce((h->>k)::integer,0)+v),true) end$$;
create or replace function private.divine_snapshot(s private.player_divine_roaming_states) returns jsonb language sql stable set search_path='' as $$select jsonb_build_object('unlocked',s.unlocked,'day',s.day_key,'used',s.used,'job',case when s.job_stage is null then null else jsonb_build_object('stageId',s.job_stage,'total',s.job_total,'completed',s.job_completed,'nextAt',extract(epoch from s.next_at)*1000,'returnRequested',s.return_requested,'pendingStageId',s.pending_stage,'pendingTotal',s.pending_total) end,'harvest',s.harvest,'revision',s.revision,'serverNow',extract(epoch from now())*1000)$$;

create or replace function private.divine_roll(h jsonb,stage integer,attempt integer) returns jsonb language plpgsql volatile set search_path='' as $$
declare rate numeric:=case when attempt<=50 then 1 when attempt<=75 then .5 else .1 end;realm integer:=ceil(stage/2.0);main_keys text[]:=array['mainlineMaterial_xuansi','mainlineMaterial_xuanjuan','mainlineMaterial_xuanpi','mainlineMaterial_lingpi','mainlineMaterial_fengpi','mainlineMaterial_lingyu','mainlineMaterial_lingjing'];herb_keys text[]:=array['craftHerbChiyuan','craftHerbXueyu','craftHerbJinjia','craftHerbQingling'];bag_low integer[][]:=array[[20,15,10,15],[25,20,12,20],[35,25,16,25],[40,30,18,30],[55,35,22,35],[65,40,26,40],[80,50,32,50],[95,55,36,55],[115,65,42,65],[135,75,48,75],[160,90,56,90],[185,100,64,100],[215,115,74,115],[245,130,84,130],[285,150,96,150],[325,170,108,170],[370,195,122,195],[420,220,140,220]];bag_high integer[][]:=array[[40,30,20,30],[50,35,24,35],[65,45,30,45],[75,50,34,50],[95,60,40,60],[110,70,46,70],[135,85,55,85],[155,95,62,95],[185,110,72,110],[215,125,82,125],[250,145,95,145],[285,165,108,165],[325,185,122,185],[365,205,138,205],[420,235,158,235],[470,260,180,260],[530,295,205,295],[600,330,230,330]];b integer[];
begin h:=private.divine_add(h,main_keys[1+floor(random()*7)::integer],1);if stage%2=1 and random()<.35*rate then h:=private.divine_add(h,main_keys[1+floor(random()*7)::integer],1);end if;if random()<(case when stage%2=0 then .75 else .3 end)*rate then h:=private.divine_add(h,'forgeTierMaterial_'||realm,1);end if;if random()<(case when stage%2=0 then .4 else .55 end)*rate then h:=private.divine_add(h,herb_keys[1+floor(random()*4)::integer],1);end if;if random()<(case when stage=18 then .7 when stage%2=0 then .6 else .3 end)*rate then h:=private.divine_add(h,'craftCinnabar',1);end if;h:=private.divine_add(h,'tribPill'||realm,1+floor(random()*2)::integer);b:=case when stage%2=0 then bag_high[stage] else bag_low[stage] end;h:=private.divine_add(h,'mainlineSpiritStoneBag',floor((b[1]+random()*(case when stage%2=0 then 1 else 1 end))*3)::integer);if random()<.75*rate then h:=private.divine_add(h,'mainlineWoodBag',b[2]);end if;if random()<.6*rate then h:=private.divine_add(h,'mainlineIronBag',b[3]);end if;if random()<.75*rate then h:=private.divine_add(h,'mainlineFoodBag',b[4]);end if;return h;end $$;

create or replace function private.divine_settle(uid uuid,p_channel text) returns private.player_divine_roaming_states language plpgsql security definer set search_path='' as $$
declare s private.player_divine_roaming_states;today date:=(timezone('Asia/Taipei',now()))::date;guard integer:=0;
begin select * into s from private.player_divine_roaming_states where user_id=uid and channel=p_channel for update;if s.day_key<>today and s.job_stage is null then s.day_key:=today;s.used:=0;end if;
 while s.job_stage is not null and s.job_completed<s.job_total and s.next_at<=now() and guard<100 and s.used<100 loop guard:=guard+1;s.used:=s.used+1;s.job_completed:=s.job_completed+1;s.harvest:=private.divine_roll(s.harvest,s.job_stage,s.used);if s.return_requested or s.job_completed>=s.job_total then s.job_stage:=null;s.job_total:=0;s.job_completed:=0;s.next_at:=null;s.return_requested:=false;s.pending_stage:=null;s.pending_total:=0;elsif s.pending_stage is not null then s.job_stage:=s.pending_stage;s.job_total:=s.pending_total;s.job_completed:=0;s.pending_stage:=null;s.pending_total:=0;s.next_at:=s.next_at+interval '15 minutes';else s.next_at:=s.next_at+interval '15 minutes';end if;end loop;
 update private.player_divine_roaming_states set day_key=s.day_key,used=s.used,job_stage=s.job_stage,job_total=s.job_total,job_completed=s.job_completed,next_at=s.next_at,return_requested=s.return_requested,pending_stage=s.pending_stage,pending_total=s.pending_total,harvest=s.harvest,revision=revision+case when guard>0 then 1 else 0 end,updated_at=now() where user_id=uid and channel=p_channel returning * into s;return s;end $$;

create or replace function public.player_divine_roaming(p_channel text,p_action text,p_stage integer default null,p_total integer default null,p_legacy_unlocked boolean default false,p_request_id uuid default null) returns jsonb language plpgsql security definer set search_path='' as $$
declare uid uuid:=(select auth.uid());s private.player_divine_roaming_states;m private.player_mainline_states;w private.player_resource_wallets;k text;v bigint;items jsonb:='{}'::jsonb;manual boolean;
begin if uid is null then raise exception '需要重新登入';end if;if p_channel not in('formal','test') or p_action not in('get','unlock_stone','start','return','claim') then raise exception '遠遊請求不正確';end if;
 insert into private.player_divine_roaming_states(user_id,channel) values(uid,p_channel) on conflict do nothing;select * into s from private.player_divine_roaming_states where user_id=uid and channel=p_channel for update;
 if not s.legacy_imported then select exists(select 1 from private.player_market_purchases where user_id=uid and channel=p_channel and offer_id='divineRoamingManual') into manual;update private.player_divine_roaming_states set unlocked=manual or coalesce(p_legacy_unlocked,false),legacy_imported=true where user_id=uid and channel=p_channel;end if;s:=private.divine_settle(uid,p_channel);
 if p_action='unlock_stone' and not s.unlocked then if p_request_id is null then raise exception '缺少請求識別碼';end if;select * into w from private.player_resource_wallets where user_id=uid and channel=p_channel for update;if w.spirit_stone<20000 then raise exception '靈石不足';end if;update private.player_resource_wallets set spirit_stone=spirit_stone-20000,revision=revision+1,updated_at=now() where user_id=uid and channel=p_channel returning * into w;update private.player_divine_roaming_states set unlocked=true,revision=revision+1 where user_id=uid and channel=p_channel returning * into s;
 elsif p_action='start' then if not s.unlocked then raise exception '尚未開通神念遠遊';end if;select * into m from private.player_mainline_states where user_id=uid and channel=p_channel;if p_stage not between 1 and m.cleared_stage or p_total<1 or p_total>100-s.used then raise exception '遠遊關卡或次數不正確';end if;if s.job_stage is null then update private.player_divine_roaming_states set job_stage=p_stage,job_total=p_total,job_completed=0,next_at=now()+interval '15 minutes',return_requested=false,revision=revision+1 where user_id=uid and channel=p_channel returning * into s;else update private.player_divine_roaming_states set pending_stage=p_stage,pending_total=p_total,return_requested=false,revision=revision+1 where user_id=uid and channel=p_channel returning * into s;end if;
 elsif p_action='return' and s.job_stage is not null then update private.player_divine_roaming_states set return_requested=true,pending_stage=null,pending_total=0,revision=revision+1 where user_id=uid and channel=p_channel returning * into s;
 elsif p_action='claim' then for k,v in select key,value::text::bigint from jsonb_each(s.harvest) loop insert into private.player_mail_item_balances(user_id,channel,item_key,amount) values(uid,p_channel,k,v) on conflict(user_id,channel,item_key) do update set amount=private.player_mail_item_balances.amount+excluded.amount,updated_at=now();end loop;select coalesce(jsonb_object_agg(item_key,amount),'{}'::jsonb) into items from private.player_mail_item_balances where user_id=uid and channel=p_channel and item_key in(select key from jsonb_each(s.harvest));update private.player_divine_roaming_states set harvest='{}',revision=revision+1 where user_id=uid and channel=p_channel returning * into s;end if;
 return jsonb_build_object('roaming',private.divine_snapshot(s),'itemBalances',items,'wallet',case when w.user_id is null then null else private.wallet_snapshot(w) end);end $$;

revoke all on function private.divine_add(jsonb,text,integer),private.divine_snapshot(private.player_divine_roaming_states),private.divine_roll(jsonb,integer,integer),private.divine_settle(uuid,text) from public,anon,authenticated;
revoke all on function public.player_divine_roaming(text,text,integer,integer,boolean,uuid) from public,anon;grant execute on function public.player_divine_roaming(text,text,integer,integer,boolean,uuid) to authenticated;
