create table if not exists private.player_jade_entitlements(user_id uuid not null references auth.users(id) on delete cascade,channel text not null check(channel in('formal','test')),entitlement_key text not null,created_at timestamptz not null default now(),primary key(user_id,channel,entitlement_key));
alter table private.player_jade_entitlements enable row level security;revoke all on private.player_jade_entitlements from public,anon,authenticated;
alter table private.player_sect_states add column if not exists transmission_until timestamptz;

create or replace function private.jade_entitlements(p_uid uuid,p_channel text) returns jsonb language sql stable set search_path='' as $$select coalesce(jsonb_agg(entitlement_key order by entitlement_key),'[]'::jsonb) from private.player_jade_entitlements where user_id=p_uid and channel=p_channel$$;
create or replace function private.sect_progress_snapshot(s private.player_sect_states) returns jsonb language sql stable set search_path='' as $$select private.sect_snapshot(s)||jsonb_build_object('sectMerit',s.sect_merit::text,'sectContribution',s.sect_contribution::text,'prestige',s.prestige::text,'sectTask',s.task_id,'transmissionUntil',s.transmission_until)$$;
create or replace function private.sect_transmission_overlap_ticks(s private.player_sect_states,p_from timestamptz,p_ticks integer) returns numeric language sql stable set search_path='' as $$select greatest(0,extract(epoch from least(p_from+make_interval(secs=>p_ticks*5),coalesce(s.transmission_until,p_from))-p_from)/5)$$;

create or replace function public.player_jade_bootstrap(p_channel text,p_legacy_balance bigint default 0) returns jsonb language plpgsql security definer set search_path='' as $$
declare uid uuid:=(select auth.uid());w private.player_jade_wallets;grant_total bigint:=0;opening bigint:=0;
begin if uid is null then raise exception '需要重新登入';end if;if p_channel not in('formal','test') then raise exception '版本不正確';end if;perform pg_advisory_xact_lock(hashtext(uid::text||'-jade-'||p_channel));insert into private.player_jade_wallets(user_id,channel) values(uid,p_channel) on conflict do nothing;select * into w from private.player_jade_wallets where user_id=uid and channel=p_channel for update;
 if not w.legacy_imported then if p_channel='formal' then select coalesce(sum(amount),0) into grant_total from public.jade_grants where user_id=uid;opening:=least(grant_total,greatest(0,coalesce(p_legacy_balance,0)));else opening:=least(99999,greatest(99999,coalesce(p_legacy_balance,0)));end if;update private.player_jade_wallets set balance=balance+opening,legacy_imported=true,revision=revision+1,updated_at=now() where user_id=uid and channel=p_channel returning * into w;insert into private.gem_ledger(user_id,channel,amount,balance_after,event_type,source_ref,metadata) values(uid,p_channel,opening,w.balance,'legacy_import','opening',jsonb_build_object('grant_cap',grant_total)) on conflict do nothing;end if;
 update public.jade_grants set status='claimed',claimed_at=coalesce(claimed_at,now()) where user_id=uid and status='pending';return private.jade_wallet_snapshot(w)||jsonb_build_object('entitlements',private.jade_entitlements(uid,p_channel));end $$;

create or replace function public.player_jade_service_purchase(p_channel text,p_service text,p_value text,p_request_id uuid) returns jsonb language plpgsql security definer set search_path='' as $$
declare uid uuid:=(select auth.uid());w private.player_jade_wallets;s private.player_sect_states;cost bigint;ent text;count_value integer;duration_seconds bigint;
begin if uid is null or p_channel not in('formal','test') or p_request_id is null then raise exception '請求資料不正確';end if;
 if p_service='outfit' then if p_value not in('女:6','女:7','女:8','男:6','男:7','男:8') then raise exception '服裝不存在';end if;cost:=50;ent:='outfit:'||p_value;
 elsif p_service='true_form' then if p_value not in('dari-buddha-hand','wanjie-demon') then raise exception '真身不存在';end if;cost:=100;ent:='true_form:'||p_value;
 elsif p_service='transmission' then count_value:=p_value::integer;if count_value=1 then cost:=5;elsif count_value=30 then cost:=120;elsif count_value=100 then cost:=300;else raise exception '傳功次數不正確';end if;duration_seconds:=count_value::bigint*9000;
 else raise exception '服務不存在';end if;
 perform pg_advisory_xact_lock(hashtext(uid::text||'-jade-service-'||p_channel));if exists(select 1 from private.gem_ledger where user_id=uid and channel=p_channel and event_type='service_purchase' and source_ref=p_request_id::text) then raise exception '重複的購買請求';end if;
 if ent is not null and exists(select 1 from private.player_jade_entitlements where user_id=uid and channel=p_channel and entitlement_key=ent) then raise exception '此項目已經擁有';end if;
 select * into w from private.player_jade_wallets where user_id=uid and channel=p_channel for update;if w.user_id is null or w.balance<cost then raise exception '靈玉不足';end if;
 if p_service='transmission' then select * into s from private.player_sect_states where user_id=uid and channel=p_channel for update;if s.user_id is null or s.sect_rank<1 then raise exception '需達內門弟子以上';end if;if coalesce(s.transmission_until,now())>now() then raise exception '掌門傳功尚在進行';end if;update private.player_sect_states set transmission_until=now()+make_interval(secs=>duration_seconds),revision=revision+1,updated_at=now() where user_id=uid and channel=p_channel returning * into s;else insert into private.player_jade_entitlements(user_id,channel,entitlement_key) values(uid,p_channel,ent);end if;
 update private.player_jade_wallets set balance=balance-cost,revision=revision+1,updated_at=now() where user_id=uid and channel=p_channel returning * into w;insert into private.gem_ledger(user_id,channel,amount,balance_after,event_type,source_ref,metadata) values(uid,p_channel,-cost,w.balance,'service_purchase',p_request_id::text,jsonb_build_object('service',p_service,'value',p_value));
 return jsonb_build_object('jade',private.jade_wallet_snapshot(w),'entitlements',private.jade_entitlements(uid,p_channel),'sect',case when s.user_id is null then null else private.sect_progress_snapshot(s) end);end $$;

drop function if exists public.arena_buy_attempt(text,text);
create or replace function public.arena_buy_attempt(p_kind text,p_channel text,p_request_id uuid default null) returns jsonb language plpgsql security definer set search_path='' as $$
declare uid uuid:=(select auth.uid());d date:=(timezone('Asia/Taipei',now()))::date;row_data public.arena_daily;rw private.player_resource_wallets;jw private.player_jade_wallets;cost bigint;
begin if uid is null or p_channel not in('formal','test') or p_kind not in('stone','jade') or p_request_id is null then raise exception 'invalid purchase';end if;perform pg_advisory_xact_lock(hashtext(uid::text||'-arena-buy-'||p_channel));if exists(select 1 from private.player_state_events where user_id=uid and channel=p_channel and request_id=p_request_id) then raise exception '重複的購買請求';end if;
 insert into public.arena_daily(user_id,channel,play_date) values(uid,p_channel,d) on conflict do nothing;select * into row_data from public.arena_daily where user_id=uid and channel=p_channel and play_date=d for update;if p_kind='stone' and row_data.stone_bought>=5 then raise exception 'stone purchase limit';end if;if p_kind='jade' and row_data.jade_bought>=5 then raise exception 'jade purchase limit';end if;
 if p_kind='stone' then cost:=5000;select * into rw from private.player_resource_wallets where user_id=uid and channel=p_channel for update;if rw.spirit_stone<cost then raise exception '靈石不足';end if;update private.player_resource_wallets set spirit_stone=spirit_stone-cost,revision=revision+1,updated_at=now() where user_id=uid and channel=p_channel returning * into rw;
 else cost:=10;select * into jw from private.player_jade_wallets where user_id=uid and channel=p_channel for update;if jw.balance<cost then raise exception '靈玉不足';end if;update private.player_jade_wallets set balance=balance-cost,revision=revision+1,updated_at=now() where user_id=uid and channel=p_channel returning * into jw;insert into private.gem_ledger(user_id,channel,amount,balance_after,event_type,source_ref,metadata) values(uid,p_channel,-cost,jw.balance,'arena_attempt',p_request_id::text,'{}');end if;
 update public.arena_daily set stone_bought=stone_bought+(p_kind='stone')::int,jade_bought=jade_bought+(p_kind='jade')::int,bought_available=bought_available+1 where user_id=uid and channel=p_channel and play_date=d returning * into row_data;insert into private.player_state_events(user_id,channel,revision,event_type,request_id,payload) values(uid,p_channel,coalesce(rw.revision,jw.revision),'arena_attempt_purchase',p_request_id,jsonb_build_object('kind',p_kind,'cost',cost));return to_jsonb(row_data)||jsonb_build_object('wallet',case when rw.user_id is null then null else private.wallet_snapshot(rw) end,'jade',case when jw.user_id is null then null else private.jade_wallet_snapshot(jw) end);end $$;

create or replace function public.player_state_claim_elapsed(p_channel text,p_expected_revision bigint,p_request_id uuid) returns jsonb language plpgsql security definer set search_path='' as $$
declare uid uuid:=(select auth.uid());started timestamptz;result jsonb;ticks integer;overlap numeric;transmission numeric;infused numeric:=0;s private.player_sect_states;c private.player_cave_states;w private.player_resource_wallets;bonus numeric:=0;reward_data jsonb;
begin select last_settled_at into started from private.player_states where user_id=uid and channel=p_channel;result:=public.player_state_claim_elapsed_sect_base(p_channel,p_expected_revision,p_request_id);ticks:=coalesce((result->>'elapsed_ticks')::integer,0);if ticks<1 then return result;end if;select * into s from private.player_sect_states where user_id=uid and channel=p_channel;select * into c from private.player_cave_states where user_id=uid and channel=p_channel;select * into w from private.player_resource_wallets where user_id=uid and channel=p_channel for update;if s.user_id is not null then overlap:=private.sect_practice_overlap_ticks(s,started,ticks);transmission:=private.sect_transmission_overlap_ticks(s,started,ticks);infused:=private.infusion_overlap_ticks(c,'qi',started,ticks);bonus:=floor(coalesce((w.earning_profile->>'cultivation_rate')::numeric,0)*(4*overlap+7*transmission+.48*least(overlap,infused)));end if;if bonus>0 then update private.player_resource_wallets set cultivation=cultivation+bonus,revision=revision+1,updated_at=now() where user_id=uid and channel=p_channel returning * into w;reward_data:=coalesce(result->'rewards','{}'::jsonb);reward_data:=jsonb_set(reward_data,'{free}',to_jsonb((coalesce((reward_data->>'free')::numeric,0)+bonus)::text));result:=result||jsonb_build_object('rewards',reward_data,'wallet_revision',w.revision);end if;return result;end $$;

create or replace function public.offline_reward_prepare(p_channel text) returns jsonb language plpgsql security definer set search_path='' as $$
declare uid uuid:=(select auth.uid());started timestamptz;segment_start timestamptz;old_ticks integer:=0;result jsonb;total_ticks integer;added_ticks integer;overlap numeric;transmission numeric;infused numeric:=0;s private.player_sect_states;c private.player_cave_states;w private.player_resource_wallets;v private.offline_reward_vaults;reward_data jsonb;bonus numeric:=0;
begin select last_settled_at into started from private.player_states where user_id=uid and channel=p_channel;select coalesce(elapsed_ticks,0) into old_ticks from private.offline_reward_vaults where user_id=uid and channel=p_channel and status='pending';result:=public.offline_reward_prepare_sect_base(p_channel);total_ticks:=coalesce((result->>'elapsed_ticks')::integer,0);added_ticks:=greatest(0,total_ticks-coalesce(old_ticks,0));if added_ticks<1 then return result;end if;segment_start:=started+make_interval(secs=>old_ticks*5);select * into s from private.player_sect_states where user_id=uid and channel=p_channel;select * into c from private.player_cave_states where user_id=uid and channel=p_channel;select * into w from private.player_resource_wallets where user_id=uid and channel=p_channel;if s.user_id is not null then overlap:=private.sect_practice_overlap_ticks(s,segment_start,added_ticks);transmission:=private.sect_transmission_overlap_ticks(s,segment_start,added_ticks);infused:=private.infusion_overlap_ticks(c,'qi',segment_start,added_ticks);bonus:=floor(coalesce((w.earning_profile->>'cultivation_rate')::numeric,0)*(4*overlap+7*transmission+.48*least(overlap,infused)));end if;if bonus>0 then select * into v from private.offline_reward_vaults where id=(result->>'vault_id')::uuid for update;reward_data:=v.rewards;reward_data:=jsonb_set(reward_data,'{free}',to_jsonb((coalesce((reward_data->>'free')::numeric,0)+bonus)::text));update private.offline_reward_vaults set rewards=reward_data,updated_at=now() where id=v.id returning * into v;result:=result||jsonb_build_object('rewards',v.rewards);end if;return result;end $$;

revoke all on function private.jade_entitlements(uuid,text),private.sect_transmission_overlap_ticks(private.player_sect_states,timestamptz,integer) from public,anon,authenticated;
revoke all on function public.player_jade_service_purchase(text,text,text,uuid),public.arena_buy_attempt(text,text,uuid) from public,anon;
grant execute on function public.player_jade_service_purchase(text,text,text,uuid),public.arena_buy_attempt(text,text,uuid) to authenticated;
