drop policy if exists player_rankings_v2_public_read on public.player_rankings_v2;
revoke select on public.player_rankings_v2 from public,anon,authenticated;

create or replace function public.player_ranking_own(p_channel text)returns jsonb language plpgsql stable security definer set search_path=''as $$declare uid uuid:=(select auth.uid());r public.player_rankings_v2;begin if uid is null then raise exception '需要重新登入';end if;if p_channel not in('formal','test')then raise exception '排行榜版本不正確';end if;select * into r from public.player_rankings_v2 where user_id=uid and channel=p_channel;if r.user_id is null then return null;end if;return jsonb_build_object('combat_power',r.combat_power,'player_name',r.player_name,'game_version',r.game_version);end$$;

create or replace function public.player_combat_rankings(p_channel text)returns table(player_name text,combat_power numeric,spirit_level integer,sword_level integer,body_level integer,updated_at timestamptz)language plpgsql stable security definer set search_path=''as $$begin if(select auth.uid())is null then raise exception '需要重新登入';end if;if p_channel not in('formal','test')then raise exception '排行榜版本不正確';end if;return query select r.player_name,r.combat_power,r.spirit_level,r.sword_level,r.body_level,r.updated_at from public.player_rankings_v2 r where r.channel=p_channel order by r.combat_power desc,r.updated_at desc limit 500;end$$;

create or replace function public.player_immortal_rankings(p_channel text)returns table(player_name text,restoration_stage integer,exploration integer,expedition_runs integer,outpost_stage integer,wasteland_progress integer,body_stage integer)language plpgsql stable security definer set search_path=''as $$begin if(select auth.uid())is null then raise exception '需要重新登入';end if;if p_channel not in('formal','test')then raise exception '排行榜版本不正確';end if;return query select coalesce(r.player_name,i.character_name,'無名仙修'),im.guide_stone_stage,least(100,jsonb_array_length(im.investigated)*15+im.guide_stone_stage*10+case when im.outer_route_cleared then 25 else 0 end),im.expedition_runs,im.wasteland_outpost_stage,coalesce((im.wasteland_route_progress->>'dryWind')::integer,0)+coalesce((im.wasteland_route_progress->>'sunken')::integer,0)+coalesce((im.wasteland_route_progress->>'kneeling')::integer,0),im.wasteland_body_stage from private.player_immortal_states im join private.player_ascension_states a on a.user_id=im.user_id and a.channel=im.channel and a.ascended left join public.player_rankings_v2 r on r.user_id=im.user_id and r.channel=im.channel left join private.player_identity_states i on i.user_id=im.user_id and i.channel=im.channel where im.channel=p_channel order by im.guide_stone_stage desc,im.wasteland_outpost_stage desc,(coalesce((im.wasteland_route_progress->>'dryWind')::integer,0)+coalesce((im.wasteland_route_progress->>'sunken')::integer,0)+coalesce((im.wasteland_route_progress->>'kneeling')::integer,0))desc,im.wasteland_body_stage desc,jsonb_array_length(im.investigated)desc,im.expedition_runs desc,im.updated_at asc limit 50;end$$;

revoke execute on function public.player_ranking_own(text),public.player_combat_rankings(text),public.player_immortal_rankings(text)from public,anon;
grant execute on function public.player_ranking_own(text),public.player_combat_rankings(text),public.player_immortal_rankings(text)to authenticated;
