create or replace function private.server_potential_totals(p_user uuid,p_channel text)returns jsonb language plpgsql stable security definer set search_path='' as $$
declare line jsonb;result jsonb:='{"trueQiFlat":0,"rootBoneFlat":0,"physiqueFlat":0,"agilityFlat":0,"trueQiPct":0,"rootBonePct":0,"physiquePct":0,"agilityPct":0,"fixedHpFlat":0,"fixedHpPct":0,"allFlat":0,"allPct":0,"lifeSteal":0}'::jsonb;t text;v numeric;
begin for line in select x.value from private.player_equipment_items e cross join lateral jsonb_array_elements(coalesce(e.potential->'main','[]'::jsonb)||coalesce(e.potential->'bonus','[]'::jsonb))x where e.user_id=p_user and e.channel=p_channel and e.equipped and e.immortal loop t:=line->>'type';v:=coalesce((line->>'value')::numeric,0);if result?t then result:=jsonb_set(result,array[t],to_jsonb((result->>t)::numeric+v),true);end if;end loop;return result;end$$;

create or replace function private.server_final_combat_core(p_user uuid,p_channel text,p_active_path text) returns jsonb language plpgsql stable security definer set search_path='' as $$
declare p private.player_progression_states;b private.player_body_states;result jsonb;book_bonus jsonb;sect_bonus jsonb;potential jsonb;k text;v numeric;qi_mult numeric:=1;flat numeric;pct numeric;
begin select * into p from private.player_progression_states where user_id=p_user and channel=p_channel;select * into b from private.player_body_states where user_id=p_user and channel=p_channel;if p_active_path not in('spirit','sword','body')or(p_active_path='spirit'and not p.spirit_path_opened)or(p_active_path='sword'and not p.sword_path_opened)or(p_active_path='body'and not p.body_path_opened)then raise exception '戰鬥快照修行道路不正確';end if;result:=private.server_component_core(p_user,p_channel);book_bonus:=private.server_book_art_bonus(p_user,p_channel);sect_bonus:=private.server_sect_art_bonus(p_user,p_channel);potential:=private.server_potential_totals(p_user,p_channel);
 foreach k in array array['trueQi','rootBone','physique','agility','spiritualPower']loop v:=coalesce((result->>k)::numeric,0)+coalesce((book_bonus->>k)::numeric,0)+coalesce((sect_bonus->>k)::numeric,0);if k='trueQi'and p.spirit_path_opened then qi_mult:=1+((case when p.qi_cycle='origin'then .06 else 0 end)+least(6,p.qi_mark_origin)*.01)*(case when p_active_path='spirit'then 1 else .5 end);v:=v*qi_mult;end if;if k='agility'and b.injury='tendon'and b.injury_until>now()then v:=v*.85;end if;if k in('trueQi','rootBone','physique','agility')then flat:=coalesce((potential->>(k||'Flat'))::numeric,0)+coalesce((potential->>'allFlat')::numeric,0);pct:=coalesce((potential->>(k||'Pct'))::numeric,0)+coalesce((potential->>'allPct')::numeric,0);v:=(v+flat)*(1+pct/100);end if;result:=jsonb_set(result,array[k],to_jsonb(greatest(0,v)),true);end loop;return result;end$$;

create or replace function private.server_combat_stats(p_user uuid,p_channel text,p_active_path text)returns jsonb language plpgsql stable security definer set search_path='' as $$
declare p private.player_progression_states;b private.player_body_states;m private.player_moral_states;core jsonb;potential jsonb;root_bone numeric;true_qi numeric;physique numeric;agility numeric;spiritual_power numeric;righteous_marks integer:=0;evil_marks integer:=0;balance_marks integer:=0;choice_count integer:=0;choice_score numeric:=0;total_moral numeric:=0;alignment_score numeric:=0;alignment_tier integer:=0;alignment_strength numeric:=0;alignment text:='unsettled';guard_power numeric:=1;attack_power numeric:=1;hp_power numeric:=1;precision numeric:=1;max_hp numeric;attack numeric;body_attack numeric;defense numeric;evasion numeric;accuracy numeric;critical numeric;damage_reduction numeric:=0;second_move numeric:=0;
begin select * into p from private.player_progression_states where user_id=p_user and channel=p_channel;select * into b from private.player_body_states where user_id=p_user and channel=p_channel;select * into m from private.player_moral_states where user_id=p_user and channel=p_channel;core:=private.server_final_combat_core(p_user,p_channel,p_active_path);potential:=private.server_potential_totals(p_user,p_channel);root_bone:=(core->>'rootBone')::numeric;true_qi:=(core->>'trueQi')::numeric;physique:=(core->>'physique')::numeric;agility:=(core->>'agility')::numeric;spiritual_power:=(core->>'spiritualPower')::numeric;
 select count(*)filter(where value#>>'{}'='righteous'),count(*)filter(where value#>>'{}'='evil'),count(*)filter(where value#>>'{}'='balance'),count(*),coalesce(sum(case value#>>'{}'when'righteous'then 2 when'evil'then-2 else 0 end),0)into righteous_marks,evil_marks,balance_marks,choice_count,choice_score from jsonb_each(coalesce(m.sword_trial_choices,'{}'::jsonb));total_moral:=coalesce(m.righteousness,0)+coalesce(m.evil_qi,0);alignment_score:=(coalesce(m.righteousness,0)-coalesce(m.evil_qi,0))/greatest(10,total_moral)+choice_score/greatest(10,choice_count*4);alignment_tier:=case when total_moral<20 then 0 when total_moral<100 then 1 when total_moral<500 then 2 else 3 end;alignment_strength:=(array[0,.04,.07,.1]::numeric[])[alignment_tier+1];if alignment_tier>0 then alignment:=case when alignment_score>=.18 then'righteous'when alignment_score<=-.18 then'evil'else'balance'end;end if;
 guard_power:=(1+least(.2,righteous_marks*.02))*case when alignment='righteous'then 1+alignment_strength else 1 end;attack_power:=case when alignment='evil'then 1+alignment_strength else 1 end;hp_power:=case when alignment='righteous'then 1+alignment_strength*.6 else 1 end;precision:=case when alignment='balance'then 1+alignment_strength else 1 end;max_hp:=round(greatest(125,120+greatest(0,root_bone)*4)*case when b.injury='internal'and b.injury_until>now()then .85 else 1 end*hp_power);max_hp:=round((max_hp+coalesce((potential->>'fixedHpFlat')::numeric,0))*(1+coalesce((potential->>'fixedHpPct')::numeric,0)/100));attack:=greatest(12,true_qi*5)*attack_power;body_attack:=greatest(12,(root_bone*2+physique*3)*(1+least(.3,floor(greatest(0,p.body_level)/4.0)*.0375)))*attack_power;defense:=greatest(0,physique*20)*guard_power;evasion:=greatest(0,agility)*3*precision;accuracy:=greatest(0,spiritual_power)*3*precision;critical:=least(.5,least(.45,(greatest(0,spiritual_power)*3)/(greatest(0,spiritual_power)*3+3000))+evil_marks*.005);damage_reduction:=case when alignment='righteous'then alignment_strength*.5 when alignment='evil'then-alignment_strength*.35 else 0 end;second_move:=case when alignment='balance'then alignment_strength else 0 end;return jsonb_build_object('maxHp',max_hp,'attack',attack,'qiAttack',attack,'bodyAttack',body_attack,'defense',defense,'evasion',evasion,'accuracy',accuracy,'crit',critical,'damageReduction',damage_reduction,'alignmentSecondMove',second_move);end$$;
revoke all on function private.server_potential_totals(uuid,text),private.server_final_combat_core(uuid,text,text),private.server_combat_stats(uuid,text,text)from public,anon,authenticated;
