create table if not exists private.player_mainline_states(user_id uuid not null references auth.users(id) on delete cascade,channel text not null check(channel in('formal','test')),cleared_stage integer not null default 0 check(cleared_stage between 0 and 18),legacy_imported boolean not null default false,revision bigint not null default 1,updated_at timestamptz not null default now(),primary key(user_id,channel));
create table if not exists private.mainline_attempts(id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users(id) on delete cascade,channel text not null check(channel in('formal','test')),stage integer not null check(stage between 1 and 18),player_power numeric not null check(player_power>=0),enemy_power numeric not null check(enemy_power>0),status text not null default 'pending' check(status in('pending','finished','expired')),won boolean,created_at timestamptz not null default now(),finished_at timestamptz);
alter table private.player_mainline_states enable row level security;alter table private.mainline_attempts enable row level security;
revoke all on private.player_mainline_states,private.mainline_attempts from public,anon,authenticated;

create or replace function private.mainline_snapshot(s private.player_mainline_states) returns jsonb language sql stable set search_path='' as $$select jsonb_build_object('clearedStage',s.cleared_stage,'revision',s.revision)$$;
create or replace function public.player_mainline_bootstrap(p_channel text,p_legacy_cleared integer default 0) returns jsonb language plpgsql security definer set search_path='' as $$
declare uid uuid:=(select auth.uid());s private.player_mainline_states;p private.player_progression_states;allowed integer;
begin if uid is null then raise exception '需要重新登入';end if;if p_channel not in('formal','test') then raise exception '版本不正確';end if;
 select * into p from private.player_progression_states where user_id=uid and channel=p_channel;if p.user_id is null then raise exception '伺服器修行進度尚未建立';end if;
 allowed:=least(18,greatest(0,(greatest(p.spirit_level,p.sword_level,p.body_level)/10+1)*2));insert into private.player_mainline_states(user_id,channel) values(uid,p_channel) on conflict do nothing;select * into s from private.player_mainline_states where user_id=uid and channel=p_channel for update;
 if not s.legacy_imported then update private.player_mainline_states set cleared_stage=least(allowed,greatest(0,coalesce(p_legacy_cleared,0))),legacy_imported=true,revision=revision+1,updated_at=now() where user_id=uid and channel=p_channel returning * into s;end if;return private.mainline_snapshot(s);end $$;

create or replace function public.player_mainline_begin(p_channel text,p_stage integer,p_request_id uuid) returns jsonb language plpgsql security definer set search_path='' as $$
declare uid uuid:=(select auth.uid());s private.player_mainline_states;p private.player_progression_states;profile public.arena_profiles;attempt uuid;power numeric;enemy_powers numeric[]:=array[1500,2000,3800,5200,10000,14500,28000,40000,78000,110000,210000,300000,560000,780000,1400000,2000000,3800000,5500000];
begin if uid is null then raise exception '需要重新登入';end if;if p_channel not in('formal','test') or p_stage not between 1 and 18 or p_request_id is null then raise exception '挑戰資料不正確';end if;
 select * into s from private.player_mainline_states where user_id=uid and channel=p_channel;select * into p from private.player_progression_states where user_id=uid and channel=p_channel;select * into profile from public.arena_profiles where user_id=uid and channel=p_channel;
 if s.user_id is null or p.user_id is null or p_stage>s.cleared_stage+1 then raise exception '此主線關卡尚未解鎖';end if;if greatest(p.spirit_level,p.sword_level,p.body_level)/10+1<ceil(p_stage/2.0) then raise exception '目前境界不足';end if;
 if profile.user_id is null or profile.snapshot->>'schema_version'<>'3' then raise exception '戰鬥快照尚未建立';end if;perform private.arena_validate_snapshot(profile.snapshot);if (profile.snapshot->'progression'->>'spirit_level')::integer>p.spirit_level or (profile.snapshot->'progression'->>'sword_level')::integer>p.sword_level or (profile.snapshot->'progression'->>'body_level')::integer>p.body_level then raise exception '戰鬥快照超出伺服器進度';end if;
 power:=(profile.snapshot->>'combat_power')::numeric;update private.mainline_attempts set status='expired' where user_id=uid and channel=p_channel and status='pending';insert into private.mainline_attempts(user_id,channel,stage,player_power,enemy_power) values(uid,p_channel,p_stage,power,enemy_powers[p_stage]) returning id into attempt;
 insert into private.player_state_events(user_id,channel,revision,event_type,request_id,payload) values(uid,p_channel,s.revision,'mainline_started',p_request_id,jsonb_build_object('attemptId',attempt,'stage',p_stage));return jsonb_build_object('attemptId',attempt,'stage',p_stage,'enemyPower',enemy_powers[p_stage],'mainline',private.mainline_snapshot(s));end $$;

create or replace function public.player_mainline_finish(p_channel text,p_attempt_id uuid,p_request_id uuid) returns jsonb language plpgsql security definer set search_path='' as $$
declare uid uuid:=(select auth.uid());a private.mainline_attempts;s private.player_mainline_states;chance numeric;server_won boolean;first_clear boolean;rewards jsonb:='{}'::jsonb;k text;v bigint;boss boolean;realm integer;primary_keys text[]:=array['mainlineMaterial_xuansi','mainlineMaterial_xuanjuan','mainlineMaterial_xuanpi','mainlineMaterial_lingpi','mainlineMaterial_fengpi','mainlineMaterial_lingyu','mainlineMaterial_lingjing'];herb_keys text[]:=array['craftHerbChiyuan','craftHerbXueyu','craftHerbJinjia','craftHerbQingling'];bag_low integer[][]:=array[[20,15,10,15],[25,20,12,20],[35,25,16,25],[40,30,18,30],[55,35,22,35],[65,40,26,40],[80,50,32,50],[95,55,36,55],[115,65,42,65],[135,75,48,75],[160,90,56,90],[185,100,64,100],[215,115,74,115],[245,130,84,130],[285,150,96,150],[325,170,108,170],[370,195,122,195],[420,220,140,220]];bag_high integer[][]:=array[[40,30,20,30],[50,35,24,35],[65,45,30,45],[75,50,34,50],[95,60,40,60],[110,70,46,70],[135,85,55,85],[155,95,62,95],[185,110,72,110],[215,125,82,125],[250,145,95,145],[285,165,108,165],[325,185,122,185],[365,205,138,205],[420,235,158,235],[470,260,180,260],[530,295,205,295],[600,330,230,330]];
begin if uid is null then raise exception '需要重新登入';end if;if p_channel not in('formal','test') or p_attempt_id is null or p_request_id is null then raise exception '結算資料不正確';end if;if exists(select 1 from private.player_state_events where user_id=uid and channel=p_channel and request_id=p_request_id) then raise exception '重複的結算請求';end if;
 select * into a from private.mainline_attempts where id=p_attempt_id and user_id=uid and channel=p_channel for update;select * into s from private.player_mainline_states where user_id=uid and channel=p_channel for update;if a.id is null or a.status<>'pending' or a.created_at<now()-interval '45 minutes' then raise exception '主線挑戰已失效';end if;if a.created_at>now()-interval '3 seconds' then raise exception '戰鬥尚未完成';end if;if a.stage>s.cleared_stage+1 then raise exception '主線進度衝突';end if;
 chance:=greatest(.1,least(.95,a.player_power/greatest(1,a.player_power+a.enemy_power)));server_won:=random()<chance;first_clear:=server_won and a.stage=s.cleared_stage+1;
 if first_clear then boss:=a.stage%2=0;realm:=ceil(a.stage/2.0);rewards:=jsonb_build_object(primary_keys[(a.stage-1)%7+1],case when boss then 2 else 1 end,'forgeTierMaterial_'||realm,case when boss then 2 else 1 end,herb_keys[(a.stage-1)%4+1],case when boss then 2 else 1 end,'craftCinnabar',case when boss then 2 else 1 end,'tribPill'||realm,case when boss then 2 else 1 end,'mainlineSpiritStoneBag',(case when boss then bag_high[a.stage][1] else bag_low[a.stage][1] end)*3,'mainlineWoodBag',case when boss then bag_high[a.stage][2] else bag_low[a.stage][2] end,'mainlineIronBag',case when boss then bag_high[a.stage][3] else bag_low[a.stage][3] end,'mainlineFoodBag',case when boss then bag_high[a.stage][4] else bag_low[a.stage][4] end);
  if boss then rewards:=jsonb_set(rewards,array[primary_keys[a.stage%7+1]],to_jsonb(coalesce((rewards->>primary_keys[a.stage%7+1])::bigint,0)+1));end if;if a.stage=18 then foreach k in array primary_keys loop rewards:=jsonb_set(rewards,array[k],to_jsonb(coalesce((rewards->>k)::bigint,0)+2));end loop;rewards:=rewards||jsonb_build_object('equipmentSpiritCore',1);end if;
  for k,v in select key,value::text::bigint from jsonb_each(rewards) loop insert into private.player_mail_item_balances(user_id,channel,item_key,amount) values(uid,p_channel,k,v) on conflict(user_id,channel,item_key) do update set amount=private.player_mail_item_balances.amount+excluded.amount,updated_at=now();end loop;update private.player_mainline_states set cleared_stage=a.stage,revision=revision+1,updated_at=now() where user_id=uid and channel=p_channel returning * into s;
 end if;update private.mainline_attempts set status='finished',won=server_won,finished_at=now() where id=a.id;insert into private.player_state_events(user_id,channel,revision,event_type,request_id,payload) values(uid,p_channel,s.revision,'mainline_resolved',p_request_id,jsonb_build_object('attemptId',a.id,'stage',a.stage,'won',server_won,'chance',chance,'firstClear',first_clear));
 return jsonb_build_object('won',server_won,'firstClear',first_clear,'mainline',private.mainline_snapshot(s),'rewards',rewards,'inventory',(select coalesce(jsonb_object_agg(item_key,amount),'{}'::jsonb) from private.player_mail_item_balances where user_id=uid and channel=p_channel and item_key in(select key from jsonb_each(rewards))));end $$;

revoke all on function private.mainline_snapshot(private.player_mainline_states) from public,anon,authenticated;
revoke all on function public.player_mainline_bootstrap(text,integer),public.player_mainline_begin(text,integer,uuid),public.player_mainline_finish(text,uuid,uuid) from public,anon;
grant execute on function public.player_mainline_bootstrap(text,integer),public.player_mainline_begin(text,integer,uuid),public.player_mainline_finish(text,uuid,uuid) to authenticated;
