alter table private.player_body_states add column if not exists trial_failures jsonb not null default '{}'::jsonb check(jsonb_typeof(trial_failures)='object');
create table if not exists private.body_trial_attempts(id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users(id) on delete cascade,channel text not null check(channel in ('formal','test')),target_level integer not null,player_power numeric not null,enemy_power numeric not null,guaranteed boolean not null default false,status text not null default 'pending' check(status in ('pending','finished','expired')),won boolean,created_at timestamptz not null default now(),finished_at timestamptz);
alter table private.body_trial_attempts enable row level security;revoke all on private.body_trial_attempts from public,anon,authenticated;

create or replace function private.body_snapshot(b private.player_body_states)
returns jsonb language sql stable set search_path='' as $$
select jsonb_build_object('revision',b.revision,'nutrition',b.nutrition,'foundations',jsonb_build_object('bone',b.foundation_bone,'blood',b.foundation_blood,'organs',b.foundation_organs),'trainingMode',b.training_mode,'nextCycleAt',case when b.next_cycle_at is null then 0 else floor(extract(epoch from b.next_cycle_at)*1000) end,'trainingLoad',b.training_load,'injury',case when b.injury_until>now() then b.injury else '' end,'injuryUntil',case when b.injury_until>now() then floor(extract(epoch from b.injury_until)*1000) else 0 end,'breakthroughValue',b.breakthrough_value,'trialFailures',b.trial_failures)
$$;

create or replace function public.player_body_trial_begin(p_channel text,p_expected_body_revision bigint,p_request_id uuid)
returns jsonb language plpgsql security definer set search_path='' as $$
declare uid uuid:=(select auth.uid());p private.player_progression_states;b private.player_body_states;profile public.arena_profiles;target integer;need numeric;failures integer;attempt_id uuid;player_power numeric;enemy_power numeric;s_spirit integer;s_sword integer;s_body integer;protected boolean;
begin
 if uid is null then raise exception 'authentication required';end if;if p_channel not in ('formal','test') or p_request_id is null then raise exception 'invalid request';end if;
 select * into p from private.player_progression_states where user_id=uid and channel=p_channel;select * into b from private.player_body_states where user_id=uid and channel=p_channel for update;select * into profile from public.arena_profiles where user_id=uid and channel=p_channel;
 if b.revision<>p_expected_body_revision then raise exception 'body revision conflict';end if;target:=p.body_level+1;if not target=any(array[16,36,56,68,88]) then raise exception 'body trial is not available';end if;need:=(array[3,3,4,4,4,5,5,6,7])[least(9,floor(p.body_level/10.0)::integer+1)];if b.foundation_bone<need or b.foundation_blood<need or b.foundation_organs<need then raise exception 'body foundations incomplete';end if;
 if profile.user_id is null then raise exception 'combat snapshot is unavailable';end if;perform private.arena_validate_snapshot(profile.snapshot);s_spirit:=(profile.snapshot->'progression'->>'spirit_level')::integer;s_sword:=(profile.snapshot->'progression'->>'sword_level')::integer;s_body:=(profile.snapshot->'progression'->>'body_level')::integer;if s_spirit>p.spirit_level or s_sword>p.sword_level or s_body>p.body_level then raise exception 'combat snapshot exceeds server progression';end if;
 failures:=greatest(0,coalesce((b.trial_failures->>target::text)::integer,0));protected:=failures>=2 and (b.injury='' or b.injury_until<=now());player_power:=(profile.snapshot->>'combat_power')::numeric;enemy_power:=ceil(player_power*(1.05+array_position(array[16,36,56,68,88],target)*.05));update private.body_trial_attempts set status='expired' where user_id=uid and channel=p_channel and status='pending';insert into private.body_trial_attempts(user_id,channel,target_level,player_power,enemy_power,guaranteed) values(uid,p_channel,target,player_power,enemy_power,protected) returning id into attempt_id;
 insert into private.player_state_events(user_id,channel,revision,event_type,request_id,payload) values(uid,p_channel,b.revision,'body_trial_started',p_request_id,jsonb_build_object('attempt_id',attempt_id,'target',target,'guaranteed',protected));return jsonb_build_object('attempt_id',attempt_id,'target_level',target,'enemy_power',enemy_power,'guaranteed',protected,'failures',failures);
end $$;

create or replace function public.player_body_trial_finish(p_channel text,p_attempt_id uuid,p_expected_progression_revision bigint,p_expected_body_revision bigint,p_request_id uuid)
returns jsonb language plpgsql security definer set search_path='' as $$
declare uid uuid:=(select auth.uid());a private.body_trial_attempts;p private.player_progression_states;b private.player_body_states;chance numeric;server_won boolean;failures integer;injury_name text;injury_seconds integer;
begin
 if uid is null then raise exception 'authentication required';end if;select * into a from private.body_trial_attempts where id=p_attempt_id and user_id=uid and channel=p_channel for update;select * into p from private.player_progression_states where user_id=uid and channel=p_channel for update;select * into b from private.player_body_states where user_id=uid and channel=p_channel for update;
 if a.id is null or a.status<>'pending' or a.created_at<now()-interval '30 minutes' then raise exception 'body trial attempt expired';end if;if a.created_at>now()-interval '3 seconds' then raise exception 'body trial is not complete';end if;if p.revision<>p_expected_progression_revision or b.revision<>p_expected_body_revision or a.target_level<>p.body_level+1 then raise exception 'progression revision conflict';end if;
 chance:=greatest(.1,least(.9,a.player_power/greatest(1,a.player_power+a.enemy_power)));server_won:=a.guaranteed or random()<chance;failures:=greatest(0,coalesce((b.trial_failures->>a.target_level::text)::integer,0));
 if server_won then update private.player_progression_states set body_level=a.target_level,revision=revision+1,updated_at=now() where user_id=uid and channel=p_channel returning * into p;update private.player_body_states set foundation_bone=0,foundation_blood=0,foundation_organs=0,training_mode='',next_cycle_at=null,breakthrough_value=0,trial_failures=jsonb_set(trial_failures,array[a.target_level::text],'0'::jsonb,true),revision=revision+1,updated_at=now() where user_id=uid and channel=p_channel returning * into b;
 else injury_name:=case when random()<.6 then 'internal' else 'tendon' end;injury_seconds:=case injury_name when 'internal' then 1800 else 2700 end;update private.player_body_states set injury=injury_name,injury_until=now()+make_interval(secs=>injury_seconds),trial_failures=jsonb_set(trial_failures,array[a.target_level::text],to_jsonb(failures+1),true),revision=revision+1,updated_at=now() where user_id=uid and channel=p_channel returning * into b;end if;
 update private.body_trial_attempts set status='finished',won=server_won,finished_at=now() where id=a.id;insert into private.player_state_events(user_id,channel,revision,event_type,request_id,payload) values(uid,p_channel,p.revision,'body_trial_resolved',p_request_id,jsonb_build_object('attempt_id',a.id,'target',a.target_level,'won',server_won,'guaranteed',a.guaranteed));return jsonb_build_object('won',server_won,'target_level',a.target_level,'progression',private.progression_snapshot(p),'body',private.body_snapshot(b));
end $$;

revoke execute on function public.player_body_trial_begin(text,bigint,uuid),public.player_body_trial_finish(text,uuid,bigint,bigint,uuid) from public,anon;grant execute on function public.player_body_trial_begin(text,bigint,uuid),public.player_body_trial_finish(text,uuid,bigint,bigint,uuid) to authenticated;
