create or replace function private.recover_account_channel(p_recovery_hash text,p_channel text,p_backup_table text)returns jsonb language plpgsql security definer set search_path='' as $$
declare old_user uuid;new_user uuid:=(select auth.uid());recovered_save jsonb;a private.account_recovery_attempts;t record;failed integer;
begin if new_user is null then raise exception 'authentication required';end if;if p_channel not in('formal','test')or p_backup_table not in('public.account_recovery_backups','public.test_account_recovery_backups')then raise exception 'invalid recovery channel';end if;if p_recovery_hash!~'^[0-9a-f]{64}$'then return jsonb_build_object('recoveryError','恢復碼格式不正確');end if;perform pg_advisory_xact_lock(hashtext(new_user::text||'-account-recovery-'||p_channel));insert into private.account_recovery_attempts(requester_id,channel)values(new_user,p_channel)on conflict do nothing;select * into a from private.account_recovery_attempts where requester_id=new_user and channel=p_channel for update;if a.locked_until is not null and a.locked_until>now()then return jsonb_build_object('recoveryError','嘗試次數過多，請於兩小時後再試','lockedUntil',a.locked_until);end if;if a.window_started<now()-interval'2 hours'then update private.account_recovery_attempts set failed_count=0,window_started=now(),locked_until=null,updated_at=now()where requester_id=new_user and channel=p_channel;a.failed_count:=0;end if;
 execute format('select user_id,save_data from %s where recovery_hash=$1 for update',p_backup_table)into old_user,recovered_save using p_recovery_hash;if old_user is null then failed:=a.failed_count+1;update private.account_recovery_attempts set failed_count=failed,locked_until=case when failed>=5 then now()+interval'2 hours'else null end,updated_at=now()where requester_id=new_user and channel=p_channel;return jsonb_build_object('recoveryError',case when failed>=5 then'恢復碼連續錯誤五次，已鎖定兩小時'else'找不到此恢復碼'end,'remainingAttempts',greatest(0,5-failed));end if;if old_user=new_user then delete from private.account_recovery_attempts where requester_id=new_user and channel=p_channel;return recovered_save;end if;
 perform pg_advisory_xact_lock(hashtext(old_user::text||'-account-recovery-owner-'||p_channel));perform set_config('app.account_recovery_transfer','1',true);delete from public.arena_matches where channel=p_channel and(challenger_id=new_user or defender_id=new_user);update public.arena_matches set challenger_id=new_user where channel=p_channel and challenger_id=old_user;update public.arena_matches set defender_id=new_user where channel=p_channel and defender_id=old_user;
 for t in select c.table_schema,c.table_name,exists(select 1 from information_schema.columns cc where cc.table_schema=c.table_schema and cc.table_name=c.table_name and cc.column_name='channel')has_channel from information_schema.columns c where c.column_name='user_id'and c.table_schema in('public','private')and exists(select 1 from information_schema.tables bt where bt.table_schema=c.table_schema and bt.table_name=c.table_name and bt.table_type='BASE TABLE')and c.table_name not in('account_recovery_backups','test_account_recovery_backups','account_recovery_attempts','legacy_character_import_eligibility','arena_matches')group by c.table_schema,c.table_name order by c.table_schema,c.table_name loop if t.has_channel then execute format('delete from %I.%I where user_id=$1 and channel=$2',t.table_schema,t.table_name)using new_user,p_channel;execute format('update %I.%I set user_id=$1 where user_id=$2 and channel=$3',t.table_schema,t.table_name)using new_user,old_user,p_channel;elsif p_channel='formal'then execute format('delete from %I.%I where user_id=$1',t.table_schema,t.table_name)using new_user;execute format('update %I.%I set user_id=$1 where user_id=$2',t.table_schema,t.table_name)using new_user,old_user;end if;end loop;
 if p_channel='test'then delete from public.player_rankings_legacy where user_id=new_user and game_version like'20260902-49%';update public.player_rankings_legacy set user_id=new_user where user_id=old_user and game_version like'20260902-49%';end if;execute format('delete from %s where user_id=$1',p_backup_table)using new_user;execute format('update %s set user_id=$1,updated_at=now() where user_id=$2',p_backup_table)using new_user,old_user;delete from private.account_recovery_attempts where requester_id=new_user and channel=p_channel;return recovered_save;
exception when unique_violation then raise exception '帳號移轉資料發生衝突，請聯絡客服';end$$;

