create or replace function public.player_equipment_bootstrap_unsealed(p_channel text,p_legacy_items jsonb,p_legacy_equipped jsonb) returns jsonb language plpgsql security definer set search_path='' as $$
declare uid uuid:=(select auth.uid());profile private.player_equipment_profiles;x jsonb;legacy_id text;should_equip boolean;slot_used text[]:=array[]::text[];
begin if uid is null then raise exception '需要重新登入';end if;if p_channel not in('formal','test') or jsonb_typeof(coalesce(p_legacy_items,'[]'::jsonb))<>'array' or jsonb_array_length(coalesce(p_legacy_items,'[]'::jsonb))>500 then raise exception '裝備資料不正確';end if;perform pg_advisory_xact_lock(hashtext(uid::text||'-equipment-'||p_channel));insert into private.player_equipment_profiles(user_id,channel) values(uid,p_channel) on conflict do nothing;select * into profile from private.player_equipment_profiles where user_id=uid and channel=p_channel for update;if not profile.imported then for x in select value from jsonb_array_elements(coalesce(p_legacy_items,'[]'::jsonb)) loop legacy_id:=left(coalesce(x->>'id',''),80);if legacy_id<>'' and private.equipment_valid(x->>'slot',coalesce((x->>'tier')::integer,0),x->>'quality',coalesce((x->>'value')::integer,0),coalesce(x->'affixes','[]'::jsonb)) then should_equip:=coalesce(p_legacy_equipped->>(x->>'slot'),'')=legacy_id and not (x->>'slot'=any(slot_used));insert into private.player_equipment_items(user_id,channel,item_id,slot,tier,quality,value,affixes,equipped) values(uid,p_channel,legacy_id,x->>'slot',(x->>'tier')::integer,x->>'quality',(x->>'value')::integer,x->'affixes',should_equip) on conflict do nothing;if should_equip then slot_used:=array_append(slot_used,x->>'slot');end if;end if;end loop;update private.player_equipment_profiles set imported=true,revision=revision+1,updated_at=now() where user_id=uid and channel=p_channel;end if;return private.equipment_snapshot(uid,p_channel);exception when invalid_text_representation or numeric_value_out_of_range then raise exception '裝備資料不正確';end $$;

create or replace function public.player_equipment_forge(p_channel text,p_slot text,p_tier integer,p_quality text,p_request_id uuid) returns jsonb language plpgsql security definer set search_path='' as $$
declare uid uuid:=(select auth.uid());p private.player_progression_states;profile private.player_equipment_profiles;bounds integer[];item_value integer:=0;item_affixes jsonb:='[]'::jsonb;item_id text:=gen_random_uuid()::text;main_keys text[]:=array['mainlineMaterial_xuansi','mainlineMaterial_xuanjuan','mainlineMaterial_xuanpi','mainlineMaterial_lingpi','mainlineMaterial_fengpi','mainlineMaterial_lingyu','mainlineMaterial_lingjing'];slot_index integer:=array_position(array['crown','robe','bracer','belt','boots','pendant','ring'],p_slot);needs integer[][]:=array[[3,1,1],[4,2,1],[5,3,1],[6,4,2],[7,5,2],[8,6,3],[9,7,3],[10,8,4],[12,10,5]];max_tier integer;k text;need_amount integer;b private.player_mail_item_balances;elements text[]:=array['金','木','水','火','土'];picked text[]:=array[]::text[];element text;affix_count integer;low_value integer;high_value integer;roll integer;
begin if uid is null then raise exception '需要重新登入';end if;if p_channel not in('formal','test') or slot_index is null or p_tier not between 1 and 9 or p_quality not in('normal','rare') or p_request_id is null then raise exception '鍛造資料不正確';end if;if exists(select 1 from private.player_state_events where user_id=uid and channel=p_channel and request_id=p_request_id) then raise exception '重複的鍛造請求';end if;perform pg_advisory_xact_lock(hashtext(uid::text||'-equipment-'||p_channel));select * into p from private.player_progression_states where user_id=uid and channel=p_channel;max_tier:=least(9,greatest(p.spirit_level/10+1,p.sword_level/10+1,p.body_level/4+1));if p_tier>max_tier then raise exception '目前境界不足';end if;
 foreach k in array array[main_keys[slot_index],'forgeTierMaterial_'||p_tier]||case when p_quality='rare' then array['equipmentSpiritCore'] else array[]::text[] end loop need_amount:=case when k=main_keys[slot_index] then needs[p_tier][1] when k='forgeTierMaterial_'||p_tier then needs[p_tier][2] else needs[p_tier][3] end;select * into b from private.player_mail_item_balances where user_id=uid and channel=p_channel and item_key=k for update;if coalesce(b.amount,0)<need_amount then raise exception '製作素材不足';end if;update private.player_mail_item_balances set amount=amount-need_amount,updated_at=now() where user_id=uid and channel=p_channel and item_key=k;end loop;
 if slot_index<=5 then bounds:=private.equipment_bounds(p_tier,p_slot,p_quality);item_value:=bounds[1]+floor(random()*(bounds[2]-bounds[1]+1));else affix_count:=case when p_tier<=3 then 1 when p_tier<=6 then 2 else 3 end;low_value:=case when p_tier<=3 then 10 when p_tier<=6 then 20 else 30 end;high_value:=case when p_tier<=3 then 20 when p_tier<=6 then 50 else 80 end;for i in 1..affix_count loop loop element:=elements[1+floor(random()*5)::integer];exit when not element=any(picked);end loop;picked:=array_append(picked,element);roll:=low_value+floor(random()*(high_value-low_value+1));if p_quality='rare' then roll:=greatest(roll,low_value+floor(random()*(high_value-low_value+1)));end if;item_affixes:=item_affixes||jsonb_build_array(jsonb_build_object('element',element,'value',roll/10.0));end loop;end if;
 insert into private.player_equipment_profiles(user_id,channel,imported) values(uid,p_channel,true) on conflict do nothing;insert into private.player_equipment_items(user_id,channel,item_id,slot,tier,quality,value,affixes) values(uid,p_channel,item_id,p_slot,p_tier,p_quality,item_value,item_affixes);update private.player_equipment_profiles set revision=revision+1,updated_at=now() where user_id=uid and channel=p_channel returning * into profile;insert into private.player_state_events(user_id,channel,revision,event_type,request_id,payload) values(uid,p_channel,profile.revision,'equipment_forged',p_request_id,jsonb_build_object('itemId',item_id,'slot',p_slot,'tier',p_tier,'quality',p_quality));return private.equipment_snapshot(uid,p_channel);end $$;

revoke all on function public.player_equipment_bootstrap_unsealed(text,jsonb,jsonb) from public,anon,authenticated;
revoke execute on function public.player_equipment_forge(text,text,integer,text,uuid) from public,anon;
grant execute on function public.player_equipment_forge(text,text,integer,text,uuid) to authenticated;
