alter table private.player_art_profiles add column if not exists sword_embryo text not null default '' check(sword_embryo in('','heavy','spirit','shadow')),add column if not exists combat_moves jsonb not null default '[]'::jsonb check(jsonb_typeof(combat_moves)='array'),add column if not exists combat_imported boolean not null default false;
create or replace function private.combat_move_allowed(p_user uuid,p_channel text,p_move text,p private.player_progression_states,profile private.player_art_profiles) returns boolean language plpgsql stable security definer set search_path='' as $$declare required_level integer;v_sect_name text;begin if p_move='origin' then return p.spirit_path_opened;elsif p_move='body-origin' then return p.body_path_opened;elsif p_move like 'body-%' then required_level:=case p_move when 'body-jade-break' then 16 when 'body-mountain-crush' then 36 when 'body-myriad-calamity' then 56 when 'body-golden-boundary' then 68 when 'body-dao-incarnate' then 88 else null end;return required_level is not null and p.body_path_opened and p.body_level>=required_level;elsif p_move in('heavy-fall','heavy-rift','spirit-thread','spirit-return','shadow-stars','shadow-void') then return p.sword_path_opened and profile.sword_embryo=case when p_move like 'heavy-%' then 'heavy' when p_move like 'spirit-%' then 'spirit' else 'shadow' end and p.sword_trial_wins>=case when p_move in('heavy-rift','spirit-return','shadow-void') then 20 else 0 end;elsif p_move~'.+-2$' then v_sect_name:=regexp_replace(p_move,'-2$','');return exists(select 1 from private.player_sect_arts a where a.user_id=p_user and a.channel=p_channel and a.sect_name=v_sect_name and a.slot=2 and private.sect_slot_is_skill(a.sect_name,a.slot));end if;return false;end $$;
create or replace function private.combat_loadout_snapshot(profile private.player_art_profiles) returns jsonb language sql stable set search_path='' as $$select jsonb_build_object('revision',profile.revision,'swordEmbryo',profile.sword_embryo,'moves',profile.combat_moves)$$;

create or replace function private.arena_validate_server_progression(p_user uuid,p_channel text,p_snapshot jsonb)
returns void language plpgsql stable security definer set search_path='' as $$
declare p private.player_progression_states;e private.player_permanent_consumable_effects;profile private.player_art_profiles;core jsonb;level_total integer;cap_value numeric;k text;bonus numeric;snapshot_moves jsonb;
begin
 select * into p from private.player_progression_states where user_id=p_user and channel=p_channel;
 if p.user_id is null then raise exception '伺服器修行進度尚未建立';end if;
 if (p_snapshot->'progression'->>'spirit_level')::integer<>p.spirit_level or (p_snapshot->'progression'->>'sword_level')::integer<>p.sword_level or (p_snapshot->'progression'->>'body_level')::integer<>p.body_level then raise exception '戰鬥快照與伺服器境界不一致';end if;
 select * into profile from private.player_art_profiles where user_id=p_user and channel=p_channel;
 if profile.user_id is null or not profile.combat_imported then raise exception '伺服器戰鬥配置尚未建立';end if;
 select coalesce(jsonb_agg(value->>'id' order by ord),'[]'::jsonb) into snapshot_moves from jsonb_array_elements(coalesce(p_snapshot->'moves','[]'::jsonb)) with ordinality e(value,ord);
 if coalesce(p_snapshot->>'sword_embryo','')<>profile.sword_embryo or snapshot_moves<>profile.combat_moves then raise exception '戰鬥招式與伺服器配置不一致';end if;
 select * into e from private.player_permanent_consumable_effects where user_id=p_user and channel=p_channel;core:=p_snapshot->'core';level_total:=p.spirit_level+p.sword_level+p.body_level;
 foreach k in array array['trueQi','rootBone','physique','agility','spiritualPower'] loop
  bonus:=case when k='spiritualPower' then 0 else coalesce((e.attribute_bonuses->>k)::numeric,0) end;cap_value:=100+level_total*15+bonus;
  if coalesce((core->>k)::numeric,-1)>cap_value then raise exception '戰鬥屬性超出伺服器進度上限';end if;
 end loop;
exception when invalid_text_representation or numeric_value_out_of_range then raise exception '戰鬥快照包含無效數值';end $$;

create or replace function public.player_combat_loadout_bootstrap(p_channel text,p_legacy_embryo text,p_legacy_moves jsonb) returns jsonb language plpgsql security definer set search_path='' as $$declare uid uuid:=(select auth.uid());profile private.player_art_profiles;p private.player_progression_states;m text;moves jsonb:='[]'::jsonb;begin if uid is null then raise exception '需要重新登入';end if;if p_channel not in('formal','test') or jsonb_typeof(coalesce(p_legacy_moves,'[]'))<>'array' then raise exception '招式資料不正確';end if;perform pg_advisory_xact_lock(hashtext(uid::text||'-combat-loadout-'||p_channel));select * into profile from private.player_art_profiles where user_id=uid and channel=p_channel for update;select * into p from private.player_progression_states where user_id=uid and channel=p_channel;if profile.user_id is null or p.user_id is null then raise exception '伺服器戰鬥配置尚未建立';end if;if not profile.combat_imported then profile.sword_embryo:=case when p_legacy_embryo in('heavy','spirit','shadow') and p.sword_path_opened then p_legacy_embryo else '' end;for m in select value#>>'{}' from jsonb_array_elements(coalesce(p_legacy_moves,'[]')) loop exit when jsonb_array_length(moves)>=2;if not moves?m and private.combat_move_allowed(uid,p_channel,m,p,profile) then moves:=moves||jsonb_build_array(m);end if;end loop;if jsonb_array_length(moves)=0 then if p.spirit_path_opened then moves:='["origin"]';elsif p.body_path_opened then moves:='["body-origin"]';elsif profile.sword_embryo<>'' then moves:=jsonb_build_array(profile.sword_embryo||case profile.sword_embryo when 'heavy' then '-fall' when 'spirit' then '-thread' else '-stars' end);end if;end if;update private.player_art_profiles set sword_embryo=profile.sword_embryo,combat_moves=moves,combat_imported=true,revision=revision+1,updated_at=now() where user_id=uid and channel=p_channel returning * into profile;update private.player_cave_states set has_sword_embryo=profile.sword_embryo<>'' where user_id=uid and channel=p_channel;end if;return private.combat_loadout_snapshot(profile);end $$;

create or replace function public.player_combat_move_set(p_channel text,p_move text,p_slot integer,p_request_id uuid) returns jsonb language plpgsql security definer set search_path='' as $$declare uid uuid:=(select auth.uid());profile private.player_art_profiles;p private.player_progression_states;moves text[];other integer;tmp text;begin if uid is null then raise exception '需要重新登入';end if;if p_channel not in('formal','test') or p_slot not between 0 and 1 or p_request_id is null then raise exception '招式配置不正確';end if;if exists(select 1 from private.player_state_events where user_id=uid and channel=p_channel and request_id=p_request_id) then raise exception '重複的配置請求';end if;perform pg_advisory_xact_lock(hashtext(uid::text||'-combat-loadout-'||p_channel));select * into profile from private.player_art_profiles where user_id=uid and channel=p_channel for update;select * into p from private.player_progression_states where user_id=uid and channel=p_channel;if not private.combat_move_allowed(uid,p_channel,p_move,p,profile) then raise exception '此招式尚未解鎖';end if;select coalesce(array_agg(value#>>'{}' order by ord),array[]::text[]) into moves from jsonb_array_elements(profile.combat_moves) with ordinality e(value,ord);while cardinality(moves)<2 loop moves:=array_append(moves,'');end loop;other:=case when p_slot=0 then 2 else 1 end;if moves[other]=p_move then tmp:=moves[p_slot+1];moves[p_slot+1]:=p_move;moves[other]:=tmp;else moves[p_slot+1]:=p_move;end if;update private.player_art_profiles set combat_moves=to_jsonb(array(select x from unnest(moves) x where x<>'' limit 2)),revision=revision+1,updated_at=now() where user_id=uid and channel=p_channel returning * into profile;insert into private.player_state_events(user_id,channel,revision,event_type,request_id,payload) values(uid,p_channel,profile.revision,'combat_move_set',p_request_id,jsonb_build_object('move',p_move,'slot',p_slot));return private.combat_loadout_snapshot(profile);end $$;

create or replace function public.player_sword_embryo_set(p_channel text,p_embryo text,p_reversion boolean,p_request_id uuid) returns jsonb language plpgsql security definer set search_path='' as $$declare uid uuid:=(select auth.uid());profile private.player_art_profiles;p private.player_progression_states;b private.player_mail_item_balances;moves jsonb;first_move text;begin if uid is null then raise exception '需要重新登入';end if;if p_channel not in('formal','test') or p_embryo not in('heavy','spirit','shadow') or p_request_id is null then raise exception '劍胚資料不正確';end if;if exists(select 1 from private.player_state_events where user_id=uid and channel=p_channel and request_id=p_request_id) then raise exception '重複的劍胚請求';end if;perform pg_advisory_xact_lock(hashtext(uid::text||'-combat-loadout-'||p_channel));select * into profile from private.player_art_profiles where user_id=uid and channel=p_channel for update;select * into p from private.player_progression_states where user_id=uid and channel=p_channel;if not p.sword_path_opened then raise exception '尚未開啟淬劍之路';end if;if p_reversion then if profile.sword_embryo='' or profile.sword_embryo=p_embryo then raise exception '無需重鑄劍胚';end if;select * into b from private.player_mail_item_balances where user_id=uid and channel=p_channel and item_key='swordEmbryoReversionElixirCount' for update;if b.user_id is null or b.amount<1 then raise exception '歸元鑄胚露不足';end if;update private.player_mail_item_balances set amount=amount-1,updated_at=now() where user_id=uid and channel=p_channel and item_key='swordEmbryoReversionElixirCount' returning * into b;else if profile.sword_embryo<>'' then raise exception '本命劍胚已凝聚';end if;end if;first_move:=case p_embryo when 'heavy' then 'heavy-fall' when 'spirit' then 'spirit-thread' else 'shadow-stars' end;select coalesce(jsonb_agg(value),'[]'::jsonb) into moves from jsonb_array_elements(profile.combat_moves) value where value#>>'{}' not in('heavy-fall','heavy-rift','spirit-thread','spirit-return','shadow-stars','shadow-void');if jsonb_array_length(moves)<2 then moves:=moves||jsonb_build_array(first_move);end if;update private.player_art_profiles set sword_embryo=p_embryo,combat_moves=(select coalesce(jsonb_agg(value),'[]'::jsonb) from (select value from jsonb_array_elements(moves) value limit 2) q),revision=revision+1,updated_at=now() where user_id=uid and channel=p_channel returning * into profile;update private.player_cave_states set has_sword_embryo=true where user_id=uid and channel=p_channel;insert into private.player_state_events(user_id,channel,revision,event_type,request_id,payload) values(uid,p_channel,profile.revision,case when p_reversion then 'sword_embryo_reverted' else 'sword_embryo_chosen' end,p_request_id,jsonb_build_object('embryo',p_embryo));return jsonb_build_object('loadout',private.combat_loadout_snapshot(profile),'itemBalances',case when b.user_id is null then '{}'::jsonb else jsonb_build_object(b.item_key,b.amount) end);end $$;

revoke all on function private.combat_move_allowed(uuid,text,text,private.player_progression_states,private.player_art_profiles),private.combat_loadout_snapshot(private.player_art_profiles) from public,anon,authenticated;
revoke execute on function public.player_combat_loadout_bootstrap(text,text,jsonb),public.player_combat_move_set(text,text,integer,uuid),public.player_sword_embryo_set(text,text,boolean,uuid) from public,anon;
grant execute on function public.player_combat_loadout_bootstrap(text,text,jsonb),public.player_combat_move_set(text,text,integer,uuid),public.player_sword_embryo_set(text,text,boolean,uuid) to authenticated;
+

create or replace function public.player_combat_loadout_bootstrap(p_channel text,p_legacy_embryo text,p_legacy_moves jsonb) returns jsonb
language plpgsql security definer set search_path='' as $$
declare uid uuid:=(select auth.uid());profile private.player_art_profiles;p private.player_progression_states;m text;moves jsonb:='[]'::jsonb;
begin
 if uid is null then raise exception '需要重新登入';end if;
 if p_channel not in('formal','test') or jsonb_typeof(coalesce(p_legacy_moves,'[]'))<>'array' then raise exception '招式資料不正確';end if;
 perform pg_advisory_xact_lock(hashtext(uid::text||'-combat-loadout-'||p_channel));
 select * into profile from private.player_art_profiles where user_id=uid and channel=p_channel for update;
 select * into p from private.player_progression_states where user_id=uid and channel=p_channel;
 if profile.user_id is null or p.user_id is null then raise exception '伺服器戰鬥配置尚未建立';end if;
 if not profile.combat_imported then
  profile.sword_embryo:=case when p_legacy_embryo in('heavy','spirit','shadow') and p.sword_path_opened then p_legacy_embryo else '' end;
  profile.combat_moves:=coalesce(p_legacy_moves,'[]'::jsonb);
  profile.combat_imported:=true;
 end if;
 for m in select value#>>'{}' from jsonb_array_elements(profile.combat_moves) loop
  exit when jsonb_array_length(moves)>=2;
  if not moves?m and private.combat_move_allowed(uid,p_channel,m,p,profile) then moves:=moves||jsonb_build_array(m);end if;
 end loop;
 if jsonb_array_length(moves)=0 then
  if p.spirit_path_opened then moves:='["origin"]'::jsonb;
  elsif p.body_path_opened then moves:='["body-origin"]'::jsonb;
  elsif profile.sword_embryo<>'' then moves:=jsonb_build_array(profile.sword_embryo||case profile.sword_embryo when 'heavy' then '-fall' when 'spirit' then '-thread' else '-stars' end);
  end if;
 end if;
 if profile.sword_embryo is distinct from (select sword_embryo from private.player_art_profiles where user_id=uid and channel=p_channel) or profile.combat_moves<>moves or not (select combat_imported from private.player_art_profiles where user_id=uid and channel=p_channel) then
  update private.player_art_profiles set sword_embryo=profile.sword_embryo,combat_moves=moves,combat_imported=true,revision=revision+1,updated_at=now() where user_id=uid and channel=p_channel returning * into profile;
  update private.player_cave_states set has_sword_embryo=profile.sword_embryo<>'' where user_id=uid and channel=p_channel;
 end if;
 return private.combat_loadout_snapshot(profile);
end $$;
