create table if not exists private.player_ascension_states(
 user_id uuid not null references auth.users(id) on delete cascade,channel text not null check(channel in('formal','test')),
 route text not null default '' check(route in('','qi','sword','body')),heart_answers jsonb not null default '[]'::jsonb check(jsonb_typeof(heart_answers)='array'),
 heart_cleared boolean not null default false,heart_allocated boolean not null default false,delusion_cleared boolean not null default false,delusion_allocated boolean not null default false,road_cleared boolean not null default false,road_allocated boolean not null default false,
 pending_stage text check(pending_stage in('heart','delusion','roadEnd')),allocations jsonb not null default '{"trueQi":0,"rootBone":0,"physique":0,"agility":0}'::jsonb,
 ascended boolean not null default false,ascended_at timestamptz,ascension_rank bigint,title_id text not null default '',revision bigint not null default 1 check(revision>0),updated_at timestamptz not null default now(),primary key(user_id,channel),unique(channel,ascension_rank)
);
create table if not exists private.ascension_rank_counters(channel text primary key check(channel in('formal','test')),next_rank bigint not null default 1 check(next_rank>0));
insert into private.ascension_rank_counters(channel) values('formal'),('test') on conflict do nothing;
create table if not exists private.ascension_attempts(
 id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users(id) on delete cascade,channel text not null check(channel in('formal','test')),stage text not null check(stage in('delusion','roadEnd')),player_power numeric not null check(player_power>=0),enemy_power numeric not null check(enemy_power>0),status text not null default 'pending' check(status in('pending','finished','expired')),won boolean,created_at timestamptz not null default now(),finished_at timestamptz
);
create index if not exists ascension_attempts_owner_idx on private.ascension_attempts(user_id,channel,status,created_at desc);
alter table private.player_ascension_states enable row level security;alter table private.ascension_rank_counters enable row level security;alter table private.ascension_attempts enable row level security;
revoke all on private.player_ascension_states,private.ascension_rank_counters,private.ascension_attempts from public,anon,authenticated;

create or replace function private.ascension_reward(p_route text,p_stage text) returns integer language sql immutable set search_path='' as $$select case p_route when 'qi' then case p_stage when 'heart' then 400 when 'delusion' then 400 else 800 end when 'sword' then case p_stage when 'heart' then 600 when 'delusion' then 600 else 1200 end when 'body' then case p_stage when 'heart' then 1000 when 'delusion' then 1000 else 2000 end end$$;
create or replace function private.ascension_snapshot(s private.player_ascension_states) returns jsonb language sql stable set search_path='' as $$select jsonb_build_object('revision',s.revision,'route',case when s.route='' then 'none' else s.route end,'prologueCompleted',s.route<>'','heartAnswers',s.heart_answers,'heartTrialCompleted',s.heart_cleared,'heartRewardAllocated',s.heart_allocated,'delusionTrialCompleted',s.delusion_cleared,'delusionRewardAllocated',s.delusion_allocated,'roadEndCompleted',s.road_cleared,'roadEndRewardAllocated',s.road_allocated,'pendingReward',case when s.pending_stage is null then null else jsonb_build_object('stage',s.pending_stage,'points',private.ascension_reward(s.route,s.pending_stage)) end,'allocations',s.allocations,'ascended',s.ascended,'ascendedAt',case when s.ascended_at is null then 0 else floor(extract(epoch from s.ascended_at)*1000) end,'serverAscensionRank',coalesce(s.ascension_rank,0),'titleId',s.title_id)$$;
create or replace function private.ascension_title(p private.player_progression_states) returns text language sql immutable set search_path='' as $$select case concat_ws('-',case when p.body_level>=68 then 'body' end,case when p.spirit_level>=80 then 'qi' end,case when p.sword_level>=80 then 'sword' end) when 'qi' then 'qi-ascension' when 'sword' then 'sword-ascension' when 'body' then 'body-ascension' when 'qi-sword' then 'qi-sword-ascension' when 'body-qi' then 'qi-body-ascension' when 'body-sword' then 'sword-body-ascension' when 'body-qi-sword' then 'three-paths-ascension' else '' end$$;

create or replace function public.player_ascension_bootstrap(p_channel text) returns jsonb language plpgsql security definer set search_path='' as $$declare uid uuid:=(select auth.uid());s private.player_ascension_states;begin if uid is null then raise exception '需要重新登入';end if;if p_channel not in('formal','test') then raise exception '版本不正確';end if;insert into private.player_ascension_states(user_id,channel) values(uid,p_channel) on conflict do nothing;select * into s from private.player_ascension_states where user_id=uid and channel=p_channel;return private.ascension_snapshot(s);end$$;

create or replace function public.player_ascension_route(p_channel text,p_route text,p_request_id uuid) returns jsonb language plpgsql security definer set search_path='' as $$
declare uid uuid:=(select auth.uid());s private.player_ascension_states;p private.player_progression_states;m private.player_mainline_states;
begin if uid is null then raise exception '需要重新登入';end if;if p_channel not in('formal','test')or p_route not in('qi','sword','body')or p_request_id is null then raise exception '飛升路線不正確';end if;if exists(select 1 from private.player_state_events where user_id=uid and channel=p_channel and request_id=p_request_id)then raise exception '重複的飛升請求';end if;perform pg_advisory_xact_lock(hashtext(uid::text||'-ascension-'||p_channel));select * into s from private.player_ascension_states where user_id=uid and channel=p_channel for update;select * into p from private.player_progression_states where user_id=uid and channel=p_channel;select * into m from private.player_mainline_states where user_id=uid and channel=p_channel;if s.user_id is null or p.user_id is null or m.user_id is null then raise exception '伺服器飛升資料尚未建立';end if;if s.route<>'' then raise exception '飛升路線已鎖定';end if;if m.cleared_stage<18 then raise exception '需先通關九鎖封天第18關';end if;if(p_route='qi'and p.spirit_level<80)or(p_route='sword'and p.sword_level<80)or(p_route='body'and p.body_level<68)then raise exception '此修行道路尚未達到飛升門檻';end if;update private.player_ascension_states set route=p_route,revision=revision+1,updated_at=now()where user_id=uid and channel=p_channel returning * into s;insert into private.player_state_events(user_id,channel,revision,event_type,request_id,payload)values(uid,p_channel,s.revision,'ascension_route_chosen',p_request_id,jsonb_build_object('route',p_route));return private.ascension_snapshot(s);end$$;

create or replace function public.player_ascension_heart(p_channel text,p_answers jsonb,p_request_id uuid) returns jsonb language plpgsql security definer set search_path='' as $$
declare uid uuid:=(select auth.uid());s private.player_ascension_states;v jsonb;
begin if uid is null then raise exception '需要重新登入';end if;if p_channel not in('formal','test')or p_request_id is null or jsonb_typeof(coalesce(p_answers,'null'))<>'array'or jsonb_array_length(p_answers)<>3 then raise exception '問心答案不正確';end if;for v in select value from jsonb_array_elements(p_answers)loop if jsonb_typeof(v)<>'number'or(v#>>'{}')::integer not between 0 and 3 then raise exception '問心答案不正確';end if;end loop;if exists(select 1 from private.player_state_events where user_id=uid and channel=p_channel and request_id=p_request_id)then raise exception '重複的問心請求';end if;perform pg_advisory_xact_lock(hashtext(uid::text||'-ascension-'||p_channel));select * into s from private.player_ascension_states where user_id=uid and channel=p_channel for update;if s.user_id is null or s.route=''then raise exception '尚未選定飛升路線';end if;if s.heart_cleared then raise exception '問心陣已通關';end if;update private.player_ascension_states set heart_answers=p_answers,heart_cleared=true,pending_stage='heart',revision=revision+1,updated_at=now()where user_id=uid and channel=p_channel returning * into s;insert into private.player_state_events(user_id,channel,revision,event_type,request_id,payload)values(uid,p_channel,s.revision,'ascension_heart_cleared',p_request_id,'{}');return private.ascension_snapshot(s);exception when invalid_text_representation or numeric_value_out_of_range then raise exception '問心答案不正確';end$$;

create or replace function public.player_ascension_allocate(p_channel text,p_stage text,p_allocation jsonb,p_expected_revision bigint,p_request_id uuid) returns jsonb language plpgsql security definer set search_path='' as $$
declare uid uuid:=(select auth.uid());s private.player_ascension_states;p private.player_progression_states;k text;v integer;total integer:=0;reward integer;next_alloc jsonb;counter bigint;
begin if uid is null then raise exception '需要重新登入';end if;if p_channel not in('formal','test')or p_stage not in('heart','delusion','roadEnd')or p_request_id is null or jsonb_typeof(coalesce(p_allocation,'null'))<>'object'or not(p_allocation?&array['trueQi','rootBone','physique','agility'])then raise exception '飛升配點不正確';end if;for k in select jsonb_object_keys(p_allocation)loop if k not in('trueQi','rootBone','physique','agility')or(p_allocation->>k)!~'^[0-9]+$'then raise exception '飛升配點不正確';end if;v:=(p_allocation->>k)::integer;if v>100000 then raise exception '飛升配點超出上限';end if;total:=total+v;end loop;if exists(select 1 from private.player_state_events where user_id=uid and channel=p_channel and request_id=p_request_id)then raise exception '重複的配點請求';end if;perform pg_advisory_xact_lock(hashtext(uid::text||'-ascension-'||p_channel));select * into s from private.player_ascension_states where user_id=uid and channel=p_channel for update;if s.user_id is null or s.pending_stage is distinct from p_stage then raise exception '目前沒有可分配的飛升獎勵';end if;if p_expected_revision is not null and s.revision<>p_expected_revision then raise exception '飛升進度已在其他裝置變更';end if;reward:=private.ascension_reward(s.route,p_stage);if total<>reward then raise exception '飛升點數必須全數分配';end if;next_alloc:=jsonb_build_object('trueQi',coalesce((s.allocations->>'trueQi')::integer,0)+(p_allocation->>'trueQi')::integer,'rootBone',coalesce((s.allocations->>'rootBone')::integer,0)+(p_allocation->>'rootBone')::integer,'physique',coalesce((s.allocations->>'physique')::integer,0)+(p_allocation->>'physique')::integer,'agility',coalesce((s.allocations->>'agility')::integer,0)+(p_allocation->>'agility')::integer);
 if p_stage='roadEnd'then select * into p from private.player_progression_states where user_id=uid and channel=p_channel;select next_rank into counter from private.ascension_rank_counters where channel=p_channel for update;update private.ascension_rank_counters set next_rank=next_rank+1 where channel=p_channel;update private.player_ascension_states set allocations=next_alloc,pending_stage=null,road_allocated=true,road_cleared=true,ascended=true,ascended_at=now(),ascension_rank=counter,title_id=private.ascension_title(p),revision=revision+1,updated_at=now()where user_id=uid and channel=p_channel returning * into s;else update private.player_ascension_states set allocations=next_alloc,pending_stage=null,heart_allocated=heart_allocated or p_stage='heart',delusion_allocated=delusion_allocated or p_stage='delusion',revision=revision+1,updated_at=now()where user_id=uid and channel=p_channel returning * into s;end if;insert into private.player_state_events(user_id,channel,revision,event_type,request_id,payload)values(uid,p_channel,s.revision,'ascension_'||lower(p_stage)||'_allocated',p_request_id,jsonb_build_object('allocation',p_allocation,'rank',s.ascension_rank));return private.ascension_snapshot(s);exception when invalid_text_representation or numeric_value_out_of_range then raise exception '飛升配點不正確';end$$;

create or replace function public.player_ascension_battle_begin(p_channel text,p_stage text,p_request_id uuid) returns jsonb language plpgsql security definer set search_path='' as $$
declare uid uuid:=(select auth.uid());s private.player_ascension_states;profile public.arena_profiles;attempt uuid;power numeric;enemy numeric;
begin if uid is null then raise exception '需要重新登入';end if;if p_channel not in('formal','test')or p_stage not in('delusion','roadEnd')or p_request_id is null then raise exception '飛升戰鬥請求不正確';end if;if exists(select 1 from private.player_state_events where user_id=uid and channel=p_channel and request_id=p_request_id)then raise exception '重複的飛升戰鬥請求';end if;perform pg_advisory_xact_lock(hashtext(uid::text||'-ascension-'||p_channel));select * into s from private.player_ascension_states where user_id=uid and channel=p_channel for update;if s.user_id is null or s.ascended then raise exception '飛升戰鬥狀態不正確';end if;if(p_stage='delusion'and(not s.heart_allocated or s.delusion_cleared))or(p_stage='roadEnd'and(not s.delusion_allocated or s.road_cleared))then raise exception '飛升關卡尚未解鎖';end if;select * into profile from public.arena_profiles where user_id=uid and channel=p_channel;if profile.user_id is null then raise exception '請先同步戰鬥屬性';end if;perform private.arena_validate_snapshot(profile.snapshot);perform private.arena_validate_server_progression(uid,p_channel,profile.snapshot);power:=(profile.snapshot->>'combat_power')::numeric;enemy:=case when p_stage='delusion'then 8500000 else 10000000 end;update private.ascension_attempts set status='expired'where user_id=uid and channel=p_channel and status='pending';insert into private.ascension_attempts(user_id,channel,stage,player_power,enemy_power)values(uid,p_channel,p_stage,power,enemy)returning id into attempt;insert into private.player_state_events(user_id,channel,revision,event_type,request_id,payload)values(uid,p_channel,s.revision,'ascension_battle_started',p_request_id,jsonb_build_object('attemptId',attempt,'stage',p_stage));return jsonb_build_object('attemptId',attempt,'enemyPower',enemy,'ascension',private.ascension_snapshot(s));end$$;

create or replace function public.player_ascension_battle_finish(p_channel text,p_attempt_id uuid,p_request_id uuid) returns jsonb language plpgsql security definer set search_path='' as $$
declare uid uuid:=(select auth.uid());a private.ascension_attempts;s private.player_ascension_states;chance numeric;server_won boolean;
begin if uid is null then raise exception '需要重新登入';end if;if p_channel not in('formal','test')or p_attempt_id is null or p_request_id is null then raise exception '飛升結算請求不正確';end if;if exists(select 1 from private.player_state_events where user_id=uid and channel=p_channel and request_id=p_request_id)then raise exception '重複的飛升結算請求';end if;perform pg_advisory_xact_lock(hashtext(uid::text||'-ascension-'||p_channel));select * into a from private.ascension_attempts where id=p_attempt_id and user_id=uid and channel=p_channel for update;select * into s from private.player_ascension_states where user_id=uid and channel=p_channel for update;if a.id is null or a.status<>'pending'or a.created_at<now()-interval '45 minutes'then raise exception '飛升挑戰已失效';end if;if a.created_at>now()-interval '3 seconds'then raise exception '戰鬥尚未完成';end if;if(a.stage='delusion'and(not s.heart_allocated or s.delusion_cleared))or(a.stage='roadEnd'and(not s.delusion_allocated or s.road_cleared))then raise exception '飛升進度衝突';end if;chance:=greatest(.1,least(.9,a.player_power/greatest(1,a.player_power+a.enemy_power)));server_won:=random()<chance;update private.ascension_attempts set status='finished',won=server_won,finished_at=now()where id=a.id;if server_won then update private.player_ascension_states set delusion_cleared=delusion_cleared or a.stage='delusion',road_cleared=road_cleared or a.stage='roadEnd',pending_stage=a.stage,revision=revision+1,updated_at=now()where user_id=uid and channel=p_channel returning * into s;end if;insert into private.player_state_events(user_id,channel,revision,event_type,request_id,payload)values(uid,p_channel,s.revision,'ascension_battle_resolved',p_request_id,jsonb_build_object('attemptId',a.id,'stage',a.stage,'won',server_won,'chance',chance));return jsonb_build_object('won',server_won,'ascension',private.ascension_snapshot(s));end$$;

create or replace function public.player_ascension_rankings(p_channel text) returns table(rank bigint,player_name text,route text,ascended_at timestamptz,title_id text) language sql stable security definer set search_path='' as $$select s.ascension_rank,coalesce(r.player_name,a.player_name,'無名修士'),s.route,s.ascended_at,s.title_id from private.player_ascension_states s left join public.player_rankings r on r.user_id=s.user_id left join public.arena_profiles a on a.user_id=s.user_id and a.channel=s.channel where s.channel=p_channel and s.ascended order by s.ascension_rank limit 50$$;

create or replace function private.arena_validate_server_progression(p_user uuid,p_channel text,p_snapshot jsonb) returns void language plpgsql stable security definer set search_path='' as $$
declare p private.player_progression_states;e private.player_permanent_consumable_effects;profile private.player_art_profiles;ascn private.player_ascension_states;core jsonb;level_total integer;cap_value numeric;k text;bonus numeric;asc_bonus numeric;snapshot_moves jsonb;
begin select * into p from private.player_progression_states where user_id=p_user and channel=p_channel;if p.user_id is null then raise exception '伺服器修行進度尚未建立';end if;if(p_snapshot->'progression'->>'spirit_level')::integer<>p.spirit_level or(p_snapshot->'progression'->>'sword_level')::integer<>p.sword_level or(p_snapshot->'progression'->>'body_level')::integer<>p.body_level then raise exception '戰鬥快照與伺服器境界不一致';end if;select * into profile from private.player_art_profiles where user_id=p_user and channel=p_channel;if profile.user_id is null or not profile.combat_imported or not profile.sword_state_imported then raise exception '伺服器戰鬥配置尚未建立';end if;select coalesce(jsonb_agg(value->>'id'order by ord),'[]'::jsonb)into snapshot_moves from jsonb_array_elements(coalesce(p_snapshot->'moves','[]'::jsonb))with ordinality x(value,ord);if coalesce(p_snapshot->>'sword_embryo','')<>profile.sword_embryo or coalesce((p_snapshot->>'sword_nurture_level')::integer,-1)<>profile.sword_nurture_level or coalesce(p_snapshot->>'sword_intent_type','')<>profile.sword_intent_type or snapshot_moves<>profile.combat_moves then raise exception '戰鬥招式與伺服器配置不一致';end if;select * into e from private.player_permanent_consumable_effects where user_id=p_user and channel=p_channel;select * into ascn from private.player_ascension_states where user_id=p_user and channel=p_channel;core:=p_snapshot->'core';level_total:=p.spirit_level+p.sword_level+p.body_level;foreach k in array array['trueQi','rootBone','physique','agility','spiritualPower']loop bonus:=case when k='spiritualPower'then 0 else coalesce((e.attribute_bonuses->>k)::numeric,0)end;asc_bonus:=case when k='spiritualPower'then 0 else coalesce((ascn.allocations->>k)::numeric,0)end;cap_value:=100+level_total*15+bonus+asc_bonus;if coalesce((core->>k)::numeric,-1)>cap_value then raise exception '戰鬥屬性超出伺服器進度上限';end if;end loop;exception when invalid_text_representation or numeric_value_out_of_range then raise exception '戰鬥快照包含無效數值';end$$;

revoke all on function private.ascension_reward(text,text),private.ascension_snapshot(private.player_ascension_states),private.ascension_title(private.player_progression_states) from public,anon,authenticated;
revoke execute on function public.player_ascension_bootstrap(text),public.player_ascension_route(text,text,uuid),public.player_ascension_heart(text,jsonb,uuid),public.player_ascension_allocate(text,text,jsonb,bigint,uuid),public.player_ascension_battle_begin(text,text,uuid),public.player_ascension_battle_finish(text,uuid,uuid),public.player_ascension_rankings(text) from public,anon;
grant execute on function public.player_ascension_bootstrap(text),public.player_ascension_route(text,text,uuid),public.player_ascension_heart(text,jsonb,uuid),public.player_ascension_allocate(text,text,jsonb,bigint,uuid),public.player_ascension_battle_begin(text,text,uuid),public.player_ascension_battle_finish(text,uuid,uuid),public.player_ascension_rankings(text) to authenticated;
