alter table private.player_partner_states add column if not exists current_state text not null default'rest'check(current_state in('rest','cultivate','seclusion','travel'));
alter table private.player_partner_states add column if not exists state_started_at timestamptz;
alter table private.player_partner_states add column if not exists state_until timestamptz;
alter table private.player_partner_states add column if not exists partner_realm integer not null default 1 check(partner_realm between 1 and 9);
alter table private.player_partner_states add column if not exists cultivation_progress numeric not null default 0 check(cultivation_progress>=0);
update private.player_partner_states set state_started_at=coalesce(state_started_at,now()),state_until=coalesce(state_until,now()+interval '24 hours')where established;

create or replace function private.partner_state_duration(p_state text)returns interval language plpgsql volatile set search_path=''as $$declare low integer;high integer;years integer;begin
 if p_state='rest'then low:=48;high:=144;elsif p_state='cultivate'then low:=96;high:=240;elsif p_state='seclusion'then low:=240;high:=720;else low:=144;high:=480;end if;years:=low+24*floor(random()*((high-low)/24+1))::integer;return make_interval(secs=>years*900);end$$;

create or replace function private.resolve_partner_runtime(p_uid uuid,p_channel text)returns private.player_partner_states language plpgsql security definer set search_path=''as $$
declare s private.player_partner_states;finished_at timestamptz;years numeric;mult numeric;next_state text;roll numeric;guard integer:=0;
begin select * into s from private.player_partner_states where user_id=p_uid and channel=p_channel for update;if s.user_id is null or not s.established then return s;end if;if s.state_started_at is null or s.state_until is null then s.current_state:='rest';s.state_started_at:=now();s.state_until:=now()+interval '24 hours';end if;
 while s.state_until<=now()and guard<100 loop finished_at:=s.state_until;years:=extract(epoch from(s.state_until-s.state_started_at))/900;mult:=case s.current_state when'rest'then .75 when'cultivate'then 1 when'seclusion'then 1.1 else .95 end;s.cultivation_progress:=s.cultivation_progress+years*mult;while s.partner_realm<9 and s.cultivation_progress>=s.partner_realm*900 loop s.cultivation_progress:=s.cultivation_progress-s.partner_realm*900;s.partner_realm:=s.partner_realm+1;end loop;
  roll:=random();next_state:=case s.personality when'warm'then case when roll<.30 then'rest'when roll<.65 then'cultivate'when roll<.80 then'seclusion'else'travel'end when'reserved'then case when roll<.20 then'rest'when roll<.55 then'cultivate'when roll<.80 then'seclusion'else'travel'end when'free'then case when roll<.25 then'rest'when roll<.45 then'cultivate'when roll<.55 then'seclusion'else'travel'end else case when roll<.10 then'rest'when roll<.50 then'cultivate'when roll<.90 then'seclusion'else'travel'end end;
  if next_state=s.current_state and next_state in('seclusion','travel')then next_state:=case when next_state='seclusion'then'cultivate'else'rest'end;end if;s.current_state:=next_state;s.state_started_at:=finished_at;s.state_until:=finished_at+private.partner_state_duration(next_state);guard:=guard+1;
 end loop;
 update private.player_partner_states set current_state=s.current_state,state_started_at=s.state_started_at,state_until=s.state_until,partner_realm=s.partner_realm,cultivation_progress=s.cultivation_progress,revision=revision+(guard>0)::integer,updated_at=case when guard>0 then now()else updated_at end where user_id=p_uid and channel=p_channel returning * into s;return s;end$$;

create or replace function private.partner_snapshot(s private.player_partner_states)returns jsonb language sql stable set search_path=''as $$select jsonb_build_object('revision',s.revision,'established',s.established,'partnerName',s.partner_name,'partnerGender',s.partner_gender,'partnerRoute',s.partner_route,'personality',s.personality,'partneredAtYear',s.partnered_at_year,'partnerRealm',s.partner_realm,'cultivationProgress',s.cultivation_progress,'currentState',s.current_state,'stateStartedAt',s.state_started_at,'stateUntil',s.state_until,'activeRoute',case when s.active_until>now()then s.active_route else''end,'activeFrom',case when s.active_until>now()then s.active_from else null end,'activeUntil',case when s.active_until>now()then s.active_until else null end,'cooldownUntil',s.cooldown_until,'serverTime',now())$$;

create or replace function public.player_partner_get(p_channel text)returns jsonb language plpgsql security definer set search_path=''as $$declare uid uuid:=(select auth.uid());s private.player_partner_states;begin if uid is null or p_channel not in('formal','test')then raise exception '請求資料不正確';end if;s:=private.resolve_partner_runtime(uid,p_channel);if s.user_id is null then raise exception '道侶資料尚未建立';end if;return private.partner_snapshot(s);end$$;

create or replace function public.player_partner_practice(p_channel text,p_route text,p_request_id uuid)returns jsonb language plpgsql security definer set search_path=''as $$
declare uid uuid:=(select auth.uid());s private.player_partner_states;p private.player_progression_states;
begin if uid is null or p_channel not in('formal','test')or p_route not in('qi','sword','body')or p_request_id is null then raise exception '請求資料不正確';end if;perform pg_advisory_xact_lock(hashtext(uid::text||'-partner-'||p_channel));if exists(select 1 from private.player_state_events where user_id=uid and channel=p_channel and request_id=p_request_id)then raise exception '重複的同修請求';end if;s:=private.resolve_partner_runtime(uid,p_channel);select * into p from private.player_progression_states where user_id=uid and channel=p_channel;if s.user_id is null or not s.established then raise exception '尚未結為道侶';end if;if s.current_state not in('rest','cultivate')then raise exception '道侶目前不在洞府，無法共同修煉';end if;if s.cooldown_until>now()then raise exception '同修心境尚未平復';end if;if(p_route='qi'and not p.spirit_path_opened)or(p_route='sword'and not p.sword_path_opened)or(p_route='body'and not p.body_path_opened)then raise exception '尚未開啟此道途';end if;
 update private.player_partner_states set active_route=p_route,active_from=now(),active_until=now()+interval '24 hours',cooldown_until=now()+interval '48 hours',revision=revision+1,updated_at=now()where user_id=uid and channel=p_channel returning * into s;insert into private.player_state_events(user_id,channel,revision,event_type,request_id,payload)values(uid,p_channel,s.revision,'partner_practice_started',p_request_id,jsonb_build_object('route',p_route,'active_until',s.active_until,'cooldown_until',s.cooldown_until));return private.partner_snapshot(s);end$$;

revoke all on function private.partner_state_duration(text),private.resolve_partner_runtime(uuid,text)from public,anon,authenticated;
revoke execute on function public.player_partner_get(text),public.player_partner_practice(text,text,uuid)from public,anon;
grant execute on function public.player_partner_get(text),public.player_partner_practice(text,text,uuid)to authenticated;
