create or replace function private.arena_validate_server_progression_base(p_user uuid,p_channel text,p_snapshot jsonb) returns void language plpgsql stable security definer set search_path='' as $$
declare p private.player_progression_states;e private.player_permanent_consumable_effects;profile private.player_art_profiles;ascn private.player_ascension_states;base_core jsonb;server_core jsonb;k text;bonus numeric;asc_bonus numeric;expected numeric;snapshot_moves jsonb;
begin select * into p from private.player_progression_states where user_id=p_user and channel=p_channel;if p.user_id is null then raise exception '伺服器修行進度尚未建立';end if;if(p_snapshot->'progression'->>'spirit_level')::integer<>p.spirit_level or(p_snapshot->'progression'->>'sword_level')::integer<>p.sword_level or(p_snapshot->'progression'->>'body_level')::integer<>p.body_level then raise exception '戰鬥快照與伺服器境界不一致';end if;select * into profile from private.player_art_profiles where user_id=p_user and channel=p_channel;if profile.user_id is null or not profile.combat_imported or not profile.sword_state_imported then raise exception '伺服器戰鬥配置尚未建立';end if;select coalesce(jsonb_agg(value->>'id' order by ord),'[]'::jsonb)into snapshot_moves from jsonb_array_elements(coalesce(p_snapshot->'moves','[]'::jsonb))with ordinality x(value,ord);if coalesce(p_snapshot->>'sword_embryo','')<>profile.sword_embryo or coalesce((p_snapshot->>'sword_nurture_level')::integer,-1)<>profile.sword_nurture_level or coalesce(p_snapshot->>'sword_intent_type','')<>profile.sword_intent_type or snapshot_moves<>profile.combat_moves then raise exception '戰鬥招式與伺服器配置不一致';end if;select * into e from private.player_permanent_consumable_effects where user_id=p_user and channel=p_channel;select * into ascn from private.player_ascension_states where user_id=p_user and channel=p_channel;base_core:=p_snapshot->'base_core';if jsonb_typeof(base_core)<>'object' then raise exception '戰鬥快照缺少伺服器基礎屬性';end if;server_core:=private.server_base_core(p_user,p_channel);foreach k in array array['trueQi','rootBone','physique','agility','spiritualPower']loop bonus:=case when k='spiritualPower'then 0 else coalesce((e.attribute_bonuses->>k)::numeric,0)end;asc_bonus:=case when k='spiritualPower'then 0 else coalesce((ascn.allocations->>k)::numeric,0)end;expected:=coalesce((server_core->>k)::numeric,0)+bonus+asc_bonus;if coalesce((base_core->>k)::numeric,-1)<>expected then raise exception '戰鬥基礎屬性與伺服器紀錄不一致';end if;end loop;end $$;

create or replace function private.server_final_combat_core(p_user uuid,p_channel text,p_active_path text) returns jsonb language plpgsql stable security definer set search_path='' as $$
declare p private.player_progression_states;b private.player_body_states;result jsonb;book_bonus jsonb;sect_bonus jsonb;k text;v numeric;qi_mult numeric:=1;
begin select * into p from private.player_progression_states where user_id=p_user and channel=p_channel;select * into b from private.player_body_states where user_id=p_user and channel=p_channel;if p_active_path not in('spirit','sword','body') or(p_active_path='spirit'and not p.spirit_path_opened)or(p_active_path='sword'and not p.sword_path_opened)or(p_active_path='body'and not p.body_path_opened)then raise exception '戰鬥快照修行道路不正確';end if;result:=private.server_component_core(p_user,p_channel);book_bonus:=private.server_book_art_bonus(p_user,p_channel);sect_bonus:=private.server_sect_art_bonus(p_user,p_channel);foreach k in array array['trueQi','rootBone','physique','agility','spiritualPower']loop v:=coalesce((result->>k)::numeric,0)+coalesce((book_bonus->>k)::numeric,0)+coalesce((sect_bonus->>k)::numeric,0);if k='trueQi'and p.spirit_path_opened then qi_mult:=1+((case when p.qi_cycle='origin'then .06 else 0 end)+least(6,p.qi_mark_origin)*.01)*(case when p_active_path='spirit'then 1 else .5 end);v:=v*qi_mult;end if;if k='agility'and b.injury='tendon'and b.injury_until>now()then v:=v*.85;end if;result:=jsonb_set(result,array[k],to_jsonb(greatest(0,v)),true);end loop;return result;end $$;

alter function private.arena_validate_server_progression(uuid,text,jsonb) rename to arena_validate_server_progression_sect_arts;
create or replace function private.arena_validate_server_progression(p_user uuid,p_channel text,p_snapshot jsonb) returns void language plpgsql stable security definer set search_path='' as $$declare expected jsonb;provided jsonb;k text;begin perform private.arena_validate_server_progression_sect_arts(p_user,p_channel,p_snapshot);expected:=private.server_final_combat_core(p_user,p_channel,coalesce(p_snapshot->>'active_path',''));provided:=p_snapshot->'core';foreach k in array array['trueQi','rootBone','physique','agility','spiritualPower']loop if abs(coalesce((provided->>k)::numeric,-1)-coalesce((expected->>k)::numeric,0))>.000001 then raise exception '完整戰鬥屬性與伺服器重算結果不一致';end if;end loop;end $$;

revoke all on function private.server_final_combat_core(uuid,text,text),private.arena_validate_server_progression_sect_arts(uuid,text,jsonb),private.arena_validate_server_progression(uuid,text,jsonb) from public,anon,authenticated;

-- The exact server-side reconstruction above is the authority.  Keep only a
-- very high numeric sanity ceiling here so legitimate late-game art bonuses
-- are not rejected by the former fixed 5,000 client-era limit.
create or replace function private.arena_validate_snapshot(p_snapshot jsonb)
returns void language plpgsql immutable set search_path='' as $$
declare core jsonb;stats jsonb;progression jsonb;move jsonb;root_bone numeric;true_qi numeric;physique numeric;agility numeric;spiritual_power numeric;expected_power numeric;supplied_power numeric;spirit_level int;sword_level int;body_level int;
begin
 if p_snapshot is null or jsonb_typeof(p_snapshot) is distinct from 'object' or pg_column_size(p_snapshot)>32768 then raise exception '問道臺快照格式不正確';end if;
 if p_snapshot->>'schema_version' is distinct from '3' then raise exception '請重新整理遊戲以更新問道臺';end if;
 core:=p_snapshot->'core';stats:=p_snapshot->'stats';progression:=p_snapshot->'progression';
 if jsonb_typeof(core) is distinct from 'object' or jsonb_typeof(stats) is distinct from 'object' or jsonb_typeof(progression) is distinct from 'object' or jsonb_typeof(p_snapshot->'moves') is distinct from 'array' then raise exception '問道臺快照缺少必要資料';end if;
 if not(progression ?& array['spirit_level','sword_level','body_level'])or not(core ?& array['trueQi','rootBone','physique','agility','spiritualPower'])or not(stats ?& array['maxHp','attack','defense','evasion','accuracy','crit','qiAttack','bodyAttack'])or not(p_snapshot ?& array['eligible','combat_power'])then raise exception '問道臺快照欄位不完整';end if;
 spirit_level:=(progression->>'spirit_level')::int;sword_level:=(progression->>'sword_level')::int;body_level:=(progression->>'body_level')::int;
 if spirit_level not between 0 and 200 or sword_level not between 0 and 200 or body_level not between 0 and 200 then raise exception '修行境界超出允許範圍';end if;
 if(p_snapshot->>'eligible')::boolean is distinct from(spirit_level>=40 or sword_level>=40 or body_level>=16)then raise exception '問道臺資格資料不一致';end if;
 root_bone:=(core->>'rootBone')::numeric;true_qi:=(core->>'trueQi')::numeric;physique:=(core->>'physique')::numeric;agility:=(core->>'agility')::numeric;spiritual_power:=(core->>'spiritualPower')::numeric;
 if root_bone not between 0 and 1000000000 or true_qi not between 0 and 1000000000 or physique not between 0 and 1000000000 or agility not between 0 and 1000000000 or spiritual_power not between 0 and 1000000000 then raise exception '角色屬性數值格式不正確';end if;
 expected_power:=root_bone*10+true_qi*25+physique*20+agility*15+spiritual_power*30;supplied_power:=(p_snapshot->>'combat_power')::numeric;
 if abs(supplied_power-expected_power)>2 then raise exception '戰力與核心屬性不一致';end if;
 if(stats->>'maxHp')::numeric not between 1 and root_bone*8+1000 or(stats->>'attack')::numeric not between 1 and true_qi*15+200 or(stats->>'qiAttack')::numeric not between 1 and true_qi*15+200 or(stats->>'bodyAttack')::numeric not between 1 and(root_bone*2+physique*3)*3+200 or(stats->>'defense')::numeric not between 0 and physique*40+200 or(stats->>'evasion')::numeric not between 0 and agility*6+100 or(stats->>'accuracy')::numeric not between 0 and spiritual_power*6+100 or(stats->>'crit')::numeric not between 0 and .6 or coalesce((stats->>'damageReduction')::numeric,0)not between -.5 and .6 then raise exception '衍生戰鬥屬性不合理';end if;
 if jsonb_array_length(p_snapshot->'moves')not between 1 and 2 then raise exception '請先配置招式';end if;
 for move in select value from jsonb_array_elements(p_snapshot->'moves')loop
  if jsonb_typeof(move)is distinct from 'object' or coalesce((move->>'hits')::numeric,1)not between 1 and 10 or coalesce((move->>'basePercent')::numeric,0)not between 0 and 1000 or coalesce((move->>'min')::numeric,0)not between 0 and 10 or coalesce((move->>'max')::numeric,0)not between 0 and 10 or coalesce((move->>'balanceMultiplier')::numeric,1)not between 0 and 2 or coalesce((move->>'damageMultiplier')::numeric,1)not between 0 and 5 or coalesce((move->>'attributeDamage')::numeric,0)not between 0 and 10000000000 or coalesce((move->>'accuracyBonus')::numeric,0)not between 0 and 2 or coalesce((move->>'armorPierce')::numeric,0)not between 0 and .8 or coalesce((move->>'lifeSteal')::numeric,0)not between 0 and 1 or coalesce((move->>'guardBonus')::numeric,0)not between 0 and .75 or coalesce((move->>'repeatChance')::numeric,0)not between 0 and 1 or coalesce((move->>'repeatScale')::numeric,0)not between 0 and 1 then raise exception '招式參數超出問道臺允許範圍';end if;
 end loop;
exception when invalid_text_representation or numeric_value_out_of_range then raise exception '問道臺快照包含無效數值';
end $$;
revoke all on function private.arena_validate_snapshot(jsonb) from public,anon,authenticated;
