alter table private.player_equipment_items drop constraint if exists player_equipment_items_tier_check;
alter table private.player_equipment_items drop constraint if exists player_equipment_items_quality_check;
alter table private.player_equipment_items add constraint player_equipment_items_tier_check check(tier between 1 and 10);
alter table private.player_equipment_items add constraint player_equipment_items_quality_check check(quality in('normal','rare','immortal'));
alter table private.player_equipment_items add column if not exists immortal boolean not null default false;
alter table private.player_equipment_items add column if not exists potential jsonb not null default '{}'::jsonb check(jsonb_typeof(potential)='object');

create or replace function private.equipment_snapshot(p_user uuid,p_channel text) returns jsonb language sql stable security definer set search_path='' as $$select jsonb_build_object('revision',coalesce((select revision from private.player_equipment_profiles where user_id=p_user and channel=p_channel),0),'items',coalesce((select jsonb_agg(jsonb_build_object('id',item_id,'slot',slot,'tier',tier,'quality',quality,'value',value,'affixes',affixes,'equipped',equipped,'immortal',immortal,'potential',potential)order by created_at,item_id)from private.player_equipment_items where user_id=p_user and channel=p_channel),'[]'::jsonb))$$;

create or replace function private.immortal_potential_line(p_grade text,p_group text) returns jsonb language plpgsql volatile set search_path='' as $$
declare r numeric:=random()*100;t text;idx integer:=array_position(array['human','earth','heaven','immortal'],p_grade);v numeric;percent boolean;
begin t:=case when r<9 then 'trueQiFlat' when r<18 then 'rootBoneFlat' when r<27 then 'physiqueFlat' when r<36 then 'agilityFlat' when r<41 then 'trueQiPct' when r<46 then 'rootBonePct' when r<51 then 'physiquePct' when r<56 then 'agilityPct' when r<71 then 'fixedHpFlat' when r<79 then 'fixedHpPct' when r<84 then 'allFlat' when r<86 then 'allPct' else 'lifeSteal'end;percent:=right(t,3)='Pct'or t='lifeSteal';
 if t~'^(trueQi|rootBone|physique|agility)'then v:=case when p_group='main'then(case when percent then(array[4,7,10,13]::numeric[])[idx]else(array[500,1000,1500,2000]::numeric[])[idx]end)else(case when percent then(array[3,5,7,9]::numeric[])[idx]else(array[400,800,1200,1600]::numeric[])[idx]end)end;
 else v:=case t when 'fixedHpFlat'then(case when p_group='main'then(array[500,1000,1500,2000]::numeric[])[idx]else(array[400,800,1200,1600]::numeric[])[idx]end)when 'fixedHpPct'then(case when p_group='main'then(array[2,3,4,5]::numeric[])[idx]else(array[1,2,3,4]::numeric[])[idx]end)when 'allFlat'then(case when p_group='main'then(array[400,800,1200,1600]::numeric[])[idx]else(array[300,600,900,1200]::numeric[])[idx]end)when 'allPct'then(case when p_group='main'then(array[3,5,8,10]::numeric[])[idx]else(array[2,3,5,7]::numeric[])[idx]end)else(case when p_group='main'then(array[.3,.5,.8,1.2]::numeric[])[idx]else(array[.2,.3,.5,.8]::numeric[])[idx]end)end;end if;return jsonb_build_object('type',t,'grade',p_grade,'value',v,'percent',percent);end$$;
create or replace function private.immortal_initial_potential()returns jsonb language sql volatile set search_path='' as $$select jsonb_build_object('mainGrade','human','bonusLeadGrade','human','bonusSecondImmortal',false,'main',jsonb_build_array(private.immortal_potential_line('human','main'),private.immortal_potential_line('human','main'),private.immortal_potential_line('human','main')),'bonus',jsonb_build_array(private.immortal_potential_line('human','bonus'),private.immortal_potential_line('human','bonus'),private.immortal_potential_line('human','bonus')))$$;

alter function private.mail_reward_catalog(text,text) rename to mail_reward_catalog_pre_immortal;
create or replace function private.mail_reward_catalog(p_channel text,p_mail_id text)returns table(mail_key text,wallet_rewards jsonb,sect_rewards jsonb,item_rewards jsonb)language plpgsql stable set search_path='' as $$begin
 if p_channel='test'and p_mail_id='test-immortal-equipment-v1'then return query select p_mail_id,'{}'::jsonb,'{}'::jsonb,'{}'::jsonb;return;end if;
 if p_channel='test'and p_mail_id='test-immortal-potential-items-v1'then return query select p_mail_id,'{}'::jsonb,'{}'::jsonb,'{"immortalMainPotentialStoneCount":9999,"immortalBonusPotentialStoneCount":9999}'::jsonb;return;end if;
 return query select * from private.mail_reward_catalog_pre_immortal(p_channel,p_mail_id);
end$$;

create or replace function public.player_test_immortal_gear_claim(p_channel text)returns jsonb language plpgsql security definer set search_path='' as $$
declare uid uuid:=(select auth.uid());s text;slots text[]:=array['crown','robe','bracer','belt','boots','pendant','ring'];vals integer[]:=array[740,1110,2220,890,1480,0,0];i integer;aff jsonb;
begin if uid is null then raise exception '需要重新登入';end if;if p_channel<>'test'or not exists(select 1 from private.player_mail_claims where user_id=uid and channel='test'and mail_key='test-immortal-equipment-v1')then raise exception '測試仙裝信件尚未由伺服器確認';end if;perform pg_advisory_xact_lock(hashtext(uid::text||'-immortal-gear-test'));insert into private.player_equipment_profiles(user_id,channel,imported)values(uid,'test',true)on conflict do nothing;
 for i in 1..7 loop s:=slots[i];if not exists(select 1 from private.player_equipment_items where user_id=uid and channel='test'and immortal and slot=s)then aff:=case s when 'pendant'then '[{"element":"金","value":9},{"element":"水","value":9},{"element":"土","value":9}]'::jsonb when 'ring'then '[{"element":"木","value":9},{"element":"火","value":9},{"element":"土","value":9}]'::jsonb else '[]'::jsonb end;insert into private.player_equipment_items(user_id,channel,item_id,slot,tier,quality,value,affixes,immortal,potential)values(uid,'test','immortal-'||s||'-'||gen_random_uuid(),s,10,'immortal',vals[i],aff,true,private.immortal_initial_potential());end if;end loop;update private.player_equipment_profiles set revision=revision+1,updated_at=now()where user_id=uid and channel='test';return private.equipment_snapshot(uid,'test');end$$;

create or replace function public.player_immortal_potential_wash(p_channel text,p_item_id text,p_group text,p_request_id uuid)returns jsonb language plpgsql security definer set search_path='' as $$
declare uid uuid:=(select auth.uid());e private.player_equipment_items;p jsonb;grade text;second_immortal boolean;grades text[];stone text;i integer;lines jsonb:='[]'::jsonb;r numeric;b private.player_mail_item_balances;
begin if uid is null then raise exception '需要重新登入';end if;if p_channel not in('formal','test')or p_group not in('main','bonus')or p_request_id is null then raise exception '仙器洗煉請求不正確';end if;if exists(select 1 from private.player_state_events where user_id=uid and channel=p_channel and request_id=p_request_id)then raise exception '重複的仙器洗煉請求';end if;perform pg_advisory_xact_lock(hashtext(uid::text||'-immortal-potential-'||p_channel));select * into e from private.player_equipment_items where user_id=uid and channel=p_channel and item_id=p_item_id for update;if e.item_id is null or not e.immortal then raise exception '找不到此仙品裝備';end if;stone:=case when p_group='main'then'immortalMainPotentialStoneCount'else'immortalBonusPotentialStoneCount'end;select * into b from private.player_mail_item_balances where user_id=uid and channel=p_channel and item_key=stone for update;if coalesce(b.amount,0)<1 then raise exception '洗煉材料不足';end if;p:=e.potential;r:=random()*100;
 if p_group='main'then grade:=coalesce(p->>'mainGrade','human');grade:=case grade when 'human'then case when r<.3 then'immortal'when r<2.3 then'heaven'else'earth'end when 'earth'then case when r<.6 then'immortal'when r<8.6 then'heaven'else'earth'end when 'heaven'then case when r<2.1 then'immortal'else'heaven'end else'immortal'end;for i in 1..3 loop lines:=lines||jsonb_build_array(private.immortal_potential_line(grade,'main'));end loop;p:=p||jsonb_build_object('mainGrade',grade,'main',lines);
 else grade:=coalesce(p->>'bonusLeadGrade','human');grade:=case grade when'human'then case when r<4.76 then'earth'else'human'end when'earth'then case when r<1.96 then'heaven'else'earth'end when'heaven'then case when r<.5 then'immortal'else'heaven'end else'immortal'end;second_immortal:=coalesce((p->>'bonusSecondImmortal')::boolean,false)or(grade='immortal'and random()<.001);grades:=array[grade,case when second_immortal then'immortal'else(array['human','earth','heaven','immortal'])[greatest(1,array_position(array['human','earth','heaven','immortal'],grade)-1)]end,(array['human','earth','heaven'])[greatest(1,least(3,array_position(array['human','earth','heaven','immortal'],grade)-1))]];for i in 1..3 loop lines:=lines||jsonb_build_array(private.immortal_potential_line(grades[i],'bonus'));end loop;p:=p||jsonb_build_object('bonusLeadGrade',grade,'bonusSecondImmortal',second_immortal,'bonus',lines);end if;
 update private.player_mail_item_balances set amount=amount-1,updated_at=now()where user_id=uid and channel=p_channel and item_key=stone;update private.player_equipment_items set potential=p where user_id=uid and channel=p_channel and item_id=p_item_id;update private.player_equipment_profiles set revision=revision+1,updated_at=now()where user_id=uid and channel=p_channel;insert into private.player_state_events(user_id,channel,revision,event_type,request_id,payload)select uid,p_channel,revision,'immortal_potential_washed',p_request_id,jsonb_build_object('itemId',p_item_id,'group',p_group)from private.player_equipment_profiles where user_id=uid and channel=p_channel;return jsonb_build_object('equipment',private.equipment_snapshot(uid,p_channel),'itemBalances',jsonb_build_object(stone,b.amount-1));end$$;

revoke all on function private.immortal_potential_line(text,text),private.immortal_initial_potential(),private.mail_reward_catalog_pre_immortal(text,text)from public,anon,authenticated;
revoke execute on function public.player_test_immortal_gear_claim(text),public.player_immortal_potential_wash(text,text,text,uuid)from public,anon;
grant execute on function public.player_test_immortal_gear_claim(text),public.player_immortal_potential_wash(text,text,text,uuid)to authenticated;
