create or replace function private.server_component_core(p_user uuid,p_channel text)
returns jsonb language plpgsql stable security definer set search_path='' as $$
declare p private.player_progression_states;e private.player_permanent_consumable_effects;a private.player_ascension_states;s private.player_art_profiles;b jsonb;realm integer;n integer;tq numeric;rb numeric;ph numeric;ag numeric;sp numeric;
begin
 select * into p from private.player_progression_states where user_id=p_user and channel=p_channel;select * into e from private.player_permanent_consumable_effects where user_id=p_user and channel=p_channel;select * into a from private.player_ascension_states where user_id=p_user and channel=p_channel;select * into s from private.player_art_profiles where user_id=p_user and channel=p_channel;b:=private.server_base_core(p_user,p_channel);realm:=greatest(1,floor(p.sword_level/10.0)::integer+1);n:=coalesce(s.sword_nurture_level,0);
 tq:=(b->>'trueQi')::numeric+coalesce((e.attribute_bonuses->>'trueQi')::numeric,0)+coalesce((a.allocations->>'trueQi')::numeric,0)+coalesce((select sum(value) from private.player_equipment_items where user_id=p_user and channel=p_channel and equipped and slot='belt'),0)+case when s.sword_embryo='spirit' then n else 0 end+case when s.sword_intent_type='break' then 2*realm else 0 end;
 rb:=(b->>'rootBone')::numeric+coalesce((e.attribute_bonuses->>'rootBone')::numeric,0)+coalesce((a.allocations->>'rootBone')::numeric,0)+coalesce((select sum(value) from private.player_equipment_items where user_id=p_user and channel=p_channel and equipped and slot='bracer'),0)+case when s.sword_embryo='heavy' then 2*n else 0 end+case when s.sword_intent_type='origin' then realm else 0 end;
 ph:=(b->>'physique')::numeric+coalesce((e.attribute_bonuses->>'physique')::numeric,0)+coalesce((a.allocations->>'physique')::numeric,0)+coalesce((select sum(value) from private.player_equipment_items where user_id=p_user and channel=p_channel and equipped and slot='robe'),0)+case when s.sword_embryo='heavy' then n else 0 end+case when s.sword_intent_type in('break','origin') then realm else 0 end;
 ag:=(b->>'agility')::numeric+coalesce((e.attribute_bonuses->>'agility')::numeric,0)+coalesce((a.allocations->>'agility')::numeric,0)+coalesce((select sum(value) from private.player_equipment_items where user_id=p_user and channel=p_channel and equipped and slot='boots'),0)+case when s.sword_embryo='shadow' then 2*n else 0 end+case when s.sword_intent_type='light' then 2*realm else 0 end;
 sp:=(b->>'spiritualPower')::numeric+coalesce((select sum(value) from private.player_equipment_items where user_id=p_user and channel=p_channel and equipped and slot='crown'),0)+case when s.sword_embryo in('spirit','shadow') then n else 0 end+case when s.sword_intent_type='light' then realm else 0 end;
 return jsonb_build_object('trueQi',tq,'rootBone',rb,'physique',ph,'agility',ag,'spiritualPower',sp);
end $$;
